source/design_and_installation/quick_starts/qs_centos_vmware.rst
VMwareImages is a leftover from docs 4.4
=> orphan word VMwareImages -> default

source/design_and_installation/building_your_cloud/ignc.rst
This fixes a typo in one of the node installation commands.
=> fix typo in node installation command

source/administration/users_and_groups/manage_users.rst
=> Update manage_users.rst - typo

source/design_and_installation/quick_starts/qs_centos7_kvm.rst
just installed 4.14 on centos 7 and did some minor corrections in the quickstart guide. thanks for merging.
=> fixed some systemd service names to fit current CentOS 7 version

source/deployment/node_installation/kvm_node_installation.rst
Prompt must be coherent with text above it.
=> Add frontend parameter to ssh-keyscan

source/deployment/vmware_infrastructure_setup/datastore_setup.rst
DRS datastores can be used as individual datastores.
=> Update StorageDRS support in 5.2

source/deployment/vmware_infrastructure_setup/datastore_setup.rst
Documentation updated with Feature #4584 enhancements.
=> Update StorageDRS support info

source/operation/vm_setup/install_steps.txt
It may be run without browser via CLI, like linux systems too.
=> wget for windows alternative

source/operation/vm_setup/install_steps.txt
Please, merge after one-context-5.4.1 release.
=> Updates for Windows one-context 5.4.1

source/intro_release_notes/release_notes_hotfix/what_is_hotfix.rst
=> what_is_hotfix.rst: fix path to the packaging sources

source/deployment/open_cloud_storage_setup/ceph_ds.rst
=> Update Ceph user caps for Luminous

source/operation/vm_setup/add_content.rst, source/operation/vm_setup/install_steps.txt
Please also cherrypick the commit into one-5.4 and one-5.4-maintenance.
=> Update Linux context packages to 5.4.2.1

source/integration/system_interfaces/api.rst
=> Added new output in case of failure

source/operation/references/template.rst, source/operation/vm_management/vm_instances.rst
=> F #1548: Added Sched actions to template reference

source/intro_release_notes/concepts_terminology/intro.rst, source/intro_release_notes/release_notes/whats_new.rst
Added some info about LXD
Corrected a word
=> Update and fix doc

source/intro_release_notes/release_notes/compatibility.rst
=> B #2189: Added new functonality to the compatibility guide

source/deployment/vmware_infrastructure_setup/vcenter_driver.rst
Included info about vcenter deploy timeout and debug information. Cherry pick 5.6
=> Added information about vcenter_driver.conf

source/intro_release_notes/release_notes/resolved_issues_561.rst, source/operation/network_management/vrouter.rst
cherry-pick to master this commit: e6c221c823cdf02cf94269b2d45e0e75395ad8bf
=> F #2260: Added feature to resolved issues and changed documentation

source/operation/references/template.rst
. one-5.6-maintenance
. Should be in master
=> #149 Docu Explain Optional (O) option in USER INPUTS

source/deployment/opennebula_installation/frontend_installation.rst
fontend_address -> frontend_address
=> fontend_address -> frontend_address

source/operation/host_cluster_management/datastore_guide.rst
=> B #2246: Added COMPATIBLE_SYS_DS to datastore's documentation

source/intro_release_notes/release_notes/whats_new.rst, source/operation/vm_management/vm_instances.rst
=> F #1147: Add documentation for disk-snapshot rename

source/intro_release_notes/release_notes/resolved_issues_562.rst
apply to:
- one-5.6-maintenance
=> Docu for bug #2433

source/deployment/sunstone_setup/suns_views.rst
=> Added Vm autorefresh

source/intro_release_notes/release_notes/resolved_issues_562.rst
Apply to:
- one-5.6-maintenance
=> Docu regarding to bug #2477

source/advanced_components/cloud_bursting/azg.rst
* No more switching to classic portal
* Fix minor flaws (oned restart, weak default password)
* Update and simplify ruby snippet for listing images (no more regions in default config)
=> Update Azure Driver doc

source/deployment/node_installation/vcenter_node_installation.rst
=> gh-403: Update fw-vnc VIB/zip URLs for 5.6.1+

source/intro_release_notes/release_notes_hotfix/resolved_issues_563.rst
apply to:
-one-5.6-maintenance
=> Docu bug Network model is not working in vCenter 2474

source/deployment/open_cloud_networking_setup/vxlan.rst
applies to:
* master
* one-5.6
* one-5.6-maintenance
=> F #2161 Add documentation for vxlan_mode option

source/intro_release_notes/release_notes/compatibility.rst
=> F #2427: Added infromation for extra template into the compatibility guide

source/deployment/node_installation/kvm_node_installation.rst, source/deployment/opennebula_installation/frontend_installation.rst
Apply at least on master, but can be cherry-picked also into one-5.6 (and maintenance).
=> gh-444: Improve SELinux documentation

source/intro_release_notes/bug2687.txt, source/intro_release_notes/release_notes/compatibility.rst, source/intro_release_notes/upgrades/upgrade_38.rst, source/intro_release_notes/upgrades/upgrade_40.rst, source/intro_release_notes/upgrades/upgrade_410.rst, source/intro_release_notes/upgrades/upgrade_412.rst, source/intro_release_notes/upgrades/upgrade_414.rst, source/intro_release_notes/upgrades/upgrade_42.rst, source/intro_release_notes/upgrades/upgrade_44.rst, source/intro_release_notes/upgrades/upgrade_46.rst, source/intro_release_notes/upgrades/upgrade_48.rst, source/intro_release_notes/upgrades/upgrade_50.rst, source/intro_release_notes/upgrades/upgrade_52.rst, source/intro_release_notes/upgrades/upgrade_54.rst, source/intro_release_notes/upgrades/upgrade_56.rst
To be merged into:
- one-5.6
- one-5.6-maintenance
=> B #2687: Disk snapshots dissapearing

source/advanced_components/marketplace/migrate_images.rst
Fixed some typos/spelling errors/sentences.
=> Some typo / text fixes to migrate_images

source/deployment/open_cloud_host_setup/lxd_driver.rst, source/intro_release_notes/release_notes/platform_notes.rst
Added some info and corrected format and typos.
=> F #1684: Upate LXD doc

source/intro_release_notes/concepts_terminology/intro.rst
/images/OpenNebula_Hypervisors.png
=> Change reference to new Hypervisor image

source/deployment/open_cloud_host_setup/lxd_driver.rst, source/operation/references/template.rst
Signed-off-by: Daniel Clavijo Coca <dclavijo@opennebula.systems>
=> Upated LXD referenceinfo

source/deployment/open_cloud_storage_setup/ceph_ds.rst
=> Updated ceph requirements for lxd

source/intro_release_notes/release_notes/resolved_issues_581.rst
Fixes OpenNebula/one#3014
Fixes OpenNebula/one#3029
=> Updated resolved issues

source/integration/system_interfaces/python.rst
and change mode to 644 (was 755)
=> fix index indention for PyONE

source/deployment/open_cloud_storage_setup/lvm_drivers.rst, source/intro_release_notes/release_notes/resolved_issues_581.rst
Applies to one-5.8-maintenance + master
=> B OpenNeula/one#2981: Delete LVM disk on host from BRIDGE_LIST

source/integration/system_interfaces/api.rst
=> F #550 Error codes missed in API documentation

source/intro_release_notes/release_notes/resolved_issues_581.rst
one-5.8
master???<--I think not
=> F #2505: What's new? - Nested filters on CLI

source/deployment/open_cloud_host_setup/kvm_driver.rst
=> F #954: Improve documentation about defaults values files

source/intro_release_notes/release_notes/resolved_issues_581.rst
=> F OpenNebula/one#3167 add sunstone banner

source/intro_release_notes/release_notes/resolved_issues_582.rst
=> B OpenNebula/One#3018

source/deployment/open_cloud_host_setup/lxd_driver.rst, source/deployment/sunstone_setup/suns_advance.rst
rubyforge.org is [unavailable since 2015](https://twitter.com/evanphx/status/399552820380053505) :(
=> fix typo and broken link

source/integration/infrastructure_integration/devel-nm.rst, source/intro_release_notes/release_notes/whats_new.rst
Merge after https://github.com/OpenNebula/one/pull/3199 is merged
=> Extend vnm actions

source/deployment/node_installation/lxd_node_installation.rst
Merge when https://github.com/OpenNebula/packages/pull/69 is merged
=> F OpenNebula/packages#69 Update lxd install procedure

source/intro_release_notes/release_notes_hotfix/resolved_issues_583.rst
=> B OpenNebula/one#3280 and B OpenNebula/one#3281 fixed

source/intro_release_notes/release_notes_hotfix/resolved_issues_583.rst
merge with https://github.com/OpenNebula/one/pull/3333
=> F OpenNebula#3222: updated resolved issues

source/intro_release_notes/release_notes_hotfix/resolved_issues_583.rst
=> B # OpenNebula/one#3368: add bug

source/intro_release_notes/release_notes_hotfix/resolved_issues_583.rst
=> B # Opennebula/one#3057: add resolved_issue

source/deployment/node_installation/vcenter_node_installation.rst
=> M #-:fix path of vCenter driver configuration

source/integration/references/build_deps.rst
=> Add lib xmlrpc-c for ubuntu 18.04

source/deployment/open_cloud_storage_setup/overview.rst
Added a section with two community-supported datastores (Linstor and StorPool).
=> F #3348: Adding Community-supported Datastores

source/operation/vm_management/vcenter_specifics.rst
to merge with "master" y a "one-5.8-maintenance",
=> F #3438: adding VCENTER_HA to doc

source/intro_release_notes/release_notes_hotfix/resolved_issues_584.rst
=> F #3438: Show if vCenter cluster have activated DRS

source/intro_release_notes/release_notes_hotfix/resolved_issues_584.rst
to merge with "master" y a "one-5.8-maintenance",
=> F #3438: Show if vCenter cluster have activated HA

source/intro_release_notes/release_notes_hotfix/resolved_issues_584.rst
Merge with one-5.8-maintenance
=> B #3463: improve image delete command

source/intro_release_notes/release_notes_hotfix/resolved_issues_584.rst
Merge with one-5.8-maintenance
=> B #3444: Put right drivers when importing market app to vCenter DS

source/intro_release_notes/release_notes_hotfix/resolved_issues_584.rst
Merge with master and one-5.8-maintenance
=> B #3439: clean onevcenter messages

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#2497: whats news

source/intro_release_notes/release_notes_hotfix/resolved_issues_584.rst
=> F #1302: improve error messages on vcenter deploy

source/intro_release_notes/release_notes_hotfix/resolved_issues_584.rst
=> B OpenNebula/one#3336: fix undefined position

source/intro_release_notes/release_notes_hotfix/resolved_issues_584.rst
=> B OpenNebula/one#3221: disappear rm_ar button

source/intro_release_notes/release_notes_hotfix/resolved_issues_585.rst
=> B OpenNebula/one#3596: Update resolved issues

source/intro_release_notes/release_notes_hotfix/resolved_issues_585.rst
=> B OpenNebula/one#3597: add bug resolved issues

source/intro_release_notes/release_notes_hotfix/resolved_issues_585.rst
=> B OpenNebula/one#3120: counter group cloudv

source/intro_release_notes/release_notes_hotfix/resolved_issues_585.rst
this PR apply:
-one.5.8-maintenance
=> B OpenNebula/one#3217: select cluster vnet

source/intro_release_notes/release_notes_hotfix/resolved_issues_585.rst
=> B OpenNebula/one#3599: renamed affinity column

source/intro_release_notes/release_notes_hotfix/resolved_issues_585.rst
=> B OpenNebula/one#3241: ipv6 replaced by --

source/intro_release_notes/release_notes_hotfix/resolved_issues_585.rst
=> B #3087: show vCenter id in VLAN

source/intro_release_notes/release_notes_hotfix/resolved_issues_585.rst
=> B #3303: save deploy mode

source/deployment/open_cloud_host_setup/kvm_driver.rst, source/intro_release_notes/release_notes/whats_new.rst, source/operation/references/template.rst, source/operation/vm_management/vm_instances.rst
+ add DEV_PREFIX param for CONTEXT
=> F OpenNebula/one#2587: Docs for SD_DISK_BUS param

source/intro_release_notes/release_notes/compatibility.rst
=> B #3631: change value DEFAULT_DEVICE_PREFIX

source/deployment/vmware_infrastructure_setup/vcenter_driver.rst
=> F #1208: create doc for vCenter custom port

source/intro_release_notes/release_notes/whats_new.rst
=> F 1208 whats new

source/intro_release_notes/release_notes/whats_new.rst
=> B OpenNebula/one#3594: add and remove cluster in ds table

source/intro_release_notes/release_notes/whats_new.rst
=> B OpenNebula/One#3715: fix multiple click

source/intro_release_notes/release_notes/whats_new.rst
=> B OpenNebula/One#3109: fix empty id when this 0

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/One#2623: remove resource vdc

source/intro_release_notes/release_notes/whats_new.rst
=> B OpenNebula/One#3358: lose NIC index

source/intro_release_notes/release_notes/whats_new.rst
=> B OpenNebula/one#1400: change order columns

source/intro_release_notes/release_notes/whats_new.rst
=> B OpenNebula/One#3754: send context VNtemplate

source/intro_release_notes/release_notes/whats_new.rst
=> B OpenNebula/One#3215: add bug to whats_news

source/intro_release_notes/release_notes/whats_new.rst
=> B OpenNebula/One#3832: preserve attribute

source/deployment/open_cloud_host_setup/kvm_driver.rst
To be:
- merged into **master**
- possibly cherry-picked into **one-5.8**
=> M #-: Fix NIC/MODEL typo

source/intro_release_notes/release_notes/whats_new.rst
=> B OpenNebula/One#3614: add bug to what's news

source/intro_release_notes/release_notes/whats_new.rst
=> B #3818: whats new

source/deployment/open_cloud_host_setup/kvm_driver.rst
=> M #: Add note about CDROM hotplugging

source/operation/users_groups_management/manage_users.rst
=> M #: Add characters limitation for users

source/intro_release_notes/release_notes/whats_new.rst
=> B #3567: whats new

source/intro_release_notes/release_notes/whats_new.rst
=> B OpenNebula#One#3883: fix resize disk VM

source/intro_release_notes/release_notes/whats_new.rst
=> B OpenNebula/One#3870: show stable version

source/intro_release_notes/release_notes/whats_new.rst
=> B OpenNebula/One#3858: update CPU model  VM

source/intro_release_notes/release_notes/whats_new.rst
=> F #916: whats new

source/intro_release_notes/release_notes/whats_new.rst
=> B OpenNebula/one#3268: no show error

source/integration/infrastructure_integration/devel-im.rst
Added some applicable information to the LXD monitoring scripts.
Applies to master
=> F OpenNebula/one#1684: Update devel-im

source/integration/system_interfaces/go.rst
This PR is related to the issue: https://github.com/OpenNebula/one/issues/2940
of the one repository.
and the pull request: https://github.com/OpenNebula/one/pull/3006
Please, do not merge it until the review/merge of the above PR.
=> update goca documentation

source/intro_release_notes/release_notes/known_issues.rst
=> M #~: known issues with wild

source/deployment/node_installation/vcenter_node_installation.rst
=> M #-: vcenter permission table changed

source/advanced_components/applications_containerization/docker_appliance_usage.rst
To be merged into **master** and cherry-picked into:
- one-5.10 + one-5.10-maintenance
- one-5.8 + one-5.8-maintenance
- one-5.6 + one-5.6-maintenance
=> M #-: Update Docker Machine app. name

source/intro_release_notes/release_notes/resolved_issues_5101.rst
=> B OpenNebula/One#3751: validate by APP_ENV

source/deployment/cloud_design/open_cloud_architecture.rst, source/deployment/cloud_design/opennebula_provisioning_model.rst, source/deployment/cloud_design/overview.rst, source/deployment/cloud_design/vmware_cloud_architecture.rst
=> cloud_design edits

source/operation/network_management/manage_vnets.rst
Now sunstone and CLI only shows NSX networks when
the host attribute NSX_STATUS = OK.
=> F #3990: Comments over importable NSX networks

source/deployment/sunstone_setup/cloud_auth.rst, source/deployment/sunstone_setup/overview.rst, source/deployment/sunstone_setup/suns_advance.rst, source/deployment/sunstone_setup/suns_auth.rst, source/deployment/sunstone_setup/suns_views.rst, source/deployment/sunstone_setup/sunstone.rst
=> sunstone_setup edits

source/deployment/sunstone_setup/cloud_auth.rst, source/deployment/sunstone_setup/suns_auth.rst, source/integration/infrastructure_integration/devel-auth.rst
=> M #-: remove old sha1 references

source/deployment/sunstone_setup/sunstone.rst
=> M #: Fix malformed tables

source/deployment/authentication_setup/external_auth.rst, source/deployment/authentication_setup/ldap.rst, source/deployment/authentication_setup/ssh_auth.rst, source/deployment/authentication_setup/x509_auth.rst
=> authentication_setup edits

source/deployment/opennebula_installation/frontend_installation.rst, source/deployment/opennebula_installation/mysql_setup.rst, source/deployment/opennebula_installation/overview.rst
=> opennebula_installation edits

source/intro_release_notes/release_notes/platform_notes.rst
Applies to 5.10 and 5.10-maintenance
=> M #-: fix broken link in platform notes

source/advanced_components/cloud_bursting/azg.rst, source/advanced_components/cloud_bursting/ec2g.rst, source/advanced_components/cloud_bursting/introh.rst, source/advanced_components/cloud_bursting/oneg.rst
Some corrections and changes to make it read better.
=> Fixes for cloud_bursting

source/integration/infrastructure_integration/sd.rst, source/intro_release_notes/release_notes/compatibility.rst
Closes https://github.com/OpenNebula/one/issues/4062
=> M #OpenNebula/one:4062: Update storge drivers

source/advanced_components/ddc/install.rst, source/advanced_components/ddc/overview.rst, source/advanced_components/ddc/reference/config/overview.rst, source/advanced_components/ddc/reference/config/playbooks/default.rst, source/advanced_components/ddc/reference/config/playbooks/default_lxd.rst, source/advanced_components/ddc/reference/config/playbooks/overview.rst, source/advanced_components/ddc/reference/config/playbooks/static_vxlan.rst, source/advanced_components/ddc/reference/config/roles.rst, source/advanced_components/ddc/reference/hooks/alias_ip.rst, source/advanced_components/ddc/reference/ipam/packet.rst, source/advanced_components/ddc/reference/provision/driver/ec2.rst, source/advanced_components/ddc/reference/provision/driver/packet.rst, source/advanced_components/ddc/reference/provision/overview.rst, source/advanced_components/ddc/reference/provision/templates.rst, source/advanced_components/ddc/reference/vnet/alias_sdnat.rst, source/advanced_components/ddc/usage.rst
=> M #-: Edits for advanced_components/ddc

source/intro_release_notes/release_notes/resolved_issues_5102.rst
this PR apply:
- one.5.10-maintenance
=> B #OpenNebula/One#4096: fix login remote

source/advanced_components/ha/frontend_ha_setup.rst, source/advanced_components/ha/overview.rst
=> M #-: Edits for advanced_components/ha

source/advanced_components/public_cloud/ec2qcg.rst, source/advanced_components/public_cloud/ec2qug.rst, source/advanced_components/public_cloud/overview.rst, source/deployment/sunstone_setup/suns_auth.rst
Note several Fixme comments which need checking.
Also I replaced the proxy instructions with a reference to the sunstone ones.
=> M #-: public_cloud edits

source/intro_release_notes/release_notes/resolved_issues_5102.rst
=> F #1973: Add vCenter custom names option for VMs

source/intro_release_notes/release_notes/resolved_issues_5102.rst
=> F #2771: add to resolved issues

source/operation/vm_management/vcenter_specifics.rst
=> F #2771: add to vcenter specifics

source/intro_release_notes/release_notes/resolved_issues_5102.rst
This PR apply:
-one-5.10-maintenance
=> B OpenNebula/One#4112: fix template numa

source/intro_release_notes/release_notes/whats_new.rst
=> F #1269: adding to whats new

source/deployment/open_cloud_host_setup/lxd_driver.rst, source/deployment/opennebula_installation/frontend_installation.rst
Applicable also to
- one-5.8-maintenance
=> Update LXD docu

source/intro_release_notes/upgrades/upgrade_58.rst
The correct flag for `apt-get install` is `--only-upgrade`, not `--only-update`
=> Fix wrong ubuntu option

source/integration/system_interfaces/go.rst
- Reduced 1st example complexity
- Fixed some spelling
Applicable to one-5.10
=> M #: Fix GOCA example

source/intro_release_notes/release_notes/resolved_issues_5103.rst
=> F #1542: vCenter hot disk resize

source/advanced_components/ddc/usage.rst
=> M #-: add quotes to OpenNebula version

source/intro_release_notes/release_notes/whats_new.rst, source/operation/references/template.rst
=> F OpenNebula/one#1203: Add Azure d. to whats_new

source/intro_release_notes/release_notes/resolved_issues_5103.rst
=> B #3844: add it to resolved issues 5103

source/deployment/vmware_infrastructure_setup/vcenter_setup.rst
=> F #1188: snapshots without memory dumps

source/intro_release_notes/release_notes_hotfix/resolved_issues_5103.rst
=> B #4194: vCenter context refresh NIC(alias)

source/advanced_components/ddc/reference/provision/driver/ec2.rst, source/advanced_components/ddc/reference/provision/driver/packet.rst
=> F OpenNebula/one#3483: add new baremetal supported instances

source/intro_release_notes/release_notes_hotfix/resolved_issues_5104.rst
https://github.com/OpenNebula/one/issues/4337
=> B OpenNebula/one#4337: add bug to resolved issues

source/intro_release_notes/release_notes/known_issues.rst, source/intro_release_notes/release_notes_hotfix/known_issues_hotfix.rst
=> F #3930: Added security group known issue

source/intro_release_notes/release_notes_hotfix/resolved_issues_5103.rst
Signed-off-by: Ricardo Diaz <rdiaz@opennebula.systems>
=> B OpenNebula/one#4361: add bug to resolved issues

source/deployment/vmware_infrastructure_setup/nsx_setup.rst
=> B #4381: Add warning about transport zone names

source/advanced_components/application_insight/onegate_usage.rst
Signed-off-by: kvaps <kvapss@gmail.com>
ref: https://github.com/OpenNebula/one/issues/1414
=> F #1414: onegate delete request api

source/intro_release_notes/release_notes_hotfix/resolved_issues_5104.rst
=> B OpenNebula/one#4438: role in services

source/intro_release_notes/release_notes_hotfix/resolved_issues_5104.rst
=> B OpenNebula/one#4393: Add bug to resolved issues

source/intro_release_notes/release_notes_hotfix/resolved_issues_5104.rst
=> B OpenNebula/one#3615: no IPv4 with IPAM

source/intro_release_notes/release_notes_hotfix/resolved_issues_5104.rst
=> B #4207: problem with unmanage nics at deploy time

source/intro_release_notes/release_notes_hotfix/resolved_issues_5104.rst
=> F #4150: add VCENTER_TEMPLATE_NAME attribute

source/intro_release_notes/release_notes_hotfix/resolved_issues_5104.rst
=> B OpenNebula/one#2763: vCenter attributes

source/_templates/footer.html, source/_templates/thelayout.html, source/conf.py
- **one-5.10-maintenance**
- cherry-pick into **master**
=> M #-: Bump year, GA

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#3025: clean section LXD template

source/advanced_components/ddc/reference/config/playbooks/overview.rst, source/advanced_components/ddc/usage.rst, source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#4292: add documentation

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#3059: LXD marketplace attributes

source/intro_release_notes/release_notes/whats_new.rst, source/operation/vm_management/vm_instances.rst
=> F #OpenNebula/one#3971: vm charter

source/advanced_components/applications_containerization/docker_host_provision_with_docker_machine.rst, source/intro_release_notes/release_notes/whats_new.rst
=> F #4052: adding to whats new

source/intro_release_notes/release_notes/whats_new.rst, source/operation/vm_management/vcenter_specifics.rst
=> F #3316: adding to whats new

source/intro_release_notes/release_notes/whats_new.rst
=> F #3675: adding to Other Issues Solved

source/intro_release_notes/release_notes/whats_new.rst
=> F #1193: adding to whats new

source/advanced_components/ddc/install.rst, source/advanced_components/ddc/reference/provision/templates.rst, source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#4215: add new examples documentation

source/intro_release_notes/release_notes/whats_new.rst
=> B OpenNebula/one#4147: vRouter floating IP

source/intro_release_notes/release_notes/whats_new.rst, source/operation/vm_management/vcenter_specifics.rst
=> F #3912: adding to whats new

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#4327: block pwd change admin acct

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#2837: Force AR remove

source/intro_release_notes/release_notes/whats_new.rst
=> B OpenNebula/one#3604: Hide instantiate options

source/intro_release_notes/release_notes/whats_new.rst, source/operation/vm_management/vm_instances.rst
=> M #~: Add update sched_actions

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#4161: wilds VM search

source/intro_release_notes/release_notes/whats_new.rst, source/operation/references/template.rst
=> F #4474: adding to whats new

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#4474: Cores vCenter

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#1417: VM IPs Dropdown

source/intro_release_notes/release_notes/whats_new.rst
=> B #Opennebula/one#1756: real cpu

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#4453: Sec. Groups VNets

source/intro_release_notes/release_notes/whats_new.rst, source/operation/network_management/vrouter.rst
=> F OpenNebula/one#2496: Force IPv4 Cloud View

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#4290: Save State of IPs Display

source/intro_release_notes/release_notes/whats_new.rst, source/operation/vm_management/vm_templates.rst
=> F OpenNebula/one#1487: Allow TB on disks

source/intro_release_notes/release_notes/whats_new.rst, source/operation/network_management/manage_vnets.rst
=> F OpenNebula/one#3758: Add VM name in leases

source/operation/vm_management/vm_templates.rst
=> F OpenNebula/one#1487: fix label issue

source/deployment/vmware_infrastructure_setup/nsx_setup.rst, source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#4081: Move NSX attributes

source/intro_release_notes/release_notes/whats_new.rst
=> B #4734: fix Docker Machine driver breaking change

source/intro_release_notes/release_notes/whats_new.rst
=> B OpenNebula/One#2992: ip leases, vmgroups

source/operation/references/vnet_template.rst
=> M #-: How to configure Outbound QoS for OVS

source/intro_release_notes/release_notes/whats_new.rst
=> B #4004: incorrect assignation of network type NSX-V

source/operation/references/vnet_template.rst
=> M #-: Update warning of Outbound QoS for OVS

source/intro_release_notes/release_notes_community/known_issues.rst
=> M #-: Remove issue with vcenter 6.0

source/deployment/opennebula_installation/repositories.rst
hints to do refresh yum caches
=> Imrpove Community docs

source/intro_release_notes/release_notes_enterprise/resolved_issues_5121.rst
=> B OpenNebula/one#4935: Fix hashed known_hosts

source/intro_release_notes/upgrades/upgrading_single.rst
This PR applies to 5.12 and master.
=> M #-: add onedb upgrade connection parameters

source/intro_release_notes/release_notes_enterprise/resolved_issues_5121.rst
=> B OpenNebula/one#4031: Sort by used CPU and Memory

source/intro_release_notes/release_notes_enterprise/resolved_issues_5121.rst
=> B OpenNebula/one#4946: Custom Attributes on VM instantiate

source/intro_release_notes/release_notes_enterprise/resolved_issues_5121.rst
=> B OpenNebula/one#4928: Error message disk resize vcenter with snapshot

source/intro_release_notes/release_notes_enterprise/resolved_issues_5121.rst
=> B OpenNebula/one#4951: Fix Dashboard running VM quota

source/advanced_components/marketplace/container_images_usage.rst
=> M #: fix typo

source/deployment/opennebula_installation/frontend_installation.rst, source/deployment/opennebula_installation/repositories.rst
Applies to one-5.12 and master.
=> M #-: Fix repositories, update packages info

source/deployment/sunstone_setup/sunstone.rst
=> M #-: Add thresholds configuration fields on table

source/intro_release_notes/release_notes_community/known_issues.rst
this PR apply:
-one-5.12-maintenance
=> M #~: fix translate sunstone

source/deployment/open_cloud_host_setup/kvm_driver.rst, source/deployment/open_cloud_host_setup/lxd_driver.rst, source/intro_release_notes/release_notes_community/whats_new.rst, source/operation/references/template.rst
not sure if I used correct whats_new.rst file and section
=> F OpenNebula/one-ee#5015: Option to disable raw section validation

source/advanced_components/cloud_bursting/ec2g.rst
=> M #-: Put ec2 in lowercase to match the code

source/operation/references/template.rst
-> one-5.12-maintenance
-> master
=> F #5004: add support INIT_SCRIPTS vCenter

source/intro_release_notes/release_notes_enterprise/resolved_issues_5124.rst
=> F OpenNebula/one#4569: Hot disk resize on vcenter

source/operation/users_groups_management/chmod.rst
=> Update oneacl resources description

source/deployment/sunstone_setup/suns_views.rst
=> M #~: Deleting Autorefresh references

source/intro_release_notes/release_notes_community/known_issues.rst, source/intro_release_notes/release_notes_enterprise/known_issues.rst
=> M #-: known issue arguments of host_error.rb hook

source/intro_release_notes/release_notes_community/whats_new.rst
=> M #-: Add resolved issue in host_error.rb hook arg

source/deployment/sunstone_setup/sunstone.rst
=> F OpenNebula/one#2755: Guacamole Fireedge documentation

source/intro_release_notes/release_notes_enterprise/resolved_issues_5125.rst
=> B OpenNebula/one#5115: add resolved issues

source/intro_release_notes/release_notes_enterprise/resolved_issues_5125.rst
This PR apply:
-one-5.12-maintenance
=> B OpenNebula/one#5019: remote oned

source/intro_release_notes/release_notes_enterprise/resolved_issues_5125.rst
=> B OpenNebula/one#4997: Fix VM charters illegible

source/intro_release_notes/upgrades/upgrading_single.rst
=> M #-: Use VIP in monitord.conf for HA on upgrade

source/advanced_components/application_flow_and_auto-scaling/appflow_configure.rst, source/advanced_components/application_flow_and_auto-scaling/appflow_use_cli.rst, source/integration/system_interfaces/appflow_api.rst
=> M #-: make small changes in Flow docs

source/deployment/node_installation/ssh.rst
Applies to
- master
- one-5.12
- possibly one-5.12-maintenance
=> M #-: Typo in opennebula-ssh-agent.service

source/intro_release_notes/release_notes_enterprise/resolved_issues_5125.rst
This PR apply:
- one.5.12-maintenance
=> B OpenNebula/one#5016: fix vm instantiate

source/intro_release_notes/release_notes/platform_notes.rst, source/operation/vm_setup/add_content.rst, source/operation/vm_setup/install_steps.txt
To be merged to
- one-5.12
- optionally one-5.12-maintenance
=> M #-: Update Linux context packages to 5.12.0.1

source/intro_release_notes/release_notes_community/whats_new.rst
Shutdown hard overrides soft shutdown
=> F OpenNebula/one#2586: Update whats new

source/operation/vm_setup/add_content.rst, source/operation/vm_setup/install_steps.txt
To be merged into:
- **one-5.12**
- cherry-picked into **one-5.12-maintenance**
(not needed to cover master)
=> M #-: Update Linux context packages to 5.12.0.2

source/intro_release_notes/release_notes_enterprise/resolved_issues_5127.rst
=> B #5113: correct values of attributes in vCenter

source/intro_release_notes/release_notes_enterprise/resolved_issues_5127.rst
=> B OpenNebula/one#5037: Fix malformed VM IPs

source/deployment/open_cloud_host_setup/lxd_driver.rst
follow up to https://forum.opennebula.io/t/lxd-guest-disk-not-extending/8989/2
=> M #: Update LXD resize requirements

source/intro_release_notes/release_notes_enterprise/resolved_issues_5127.rst
=> F OpenNebula/One#5179: overcommit mem

source/advanced_components/application_flow_and_auto-scaling/appflow_use_cli.rst
=> M #-: Add note about service VMs

source/operation/vm_management/vcenter_specifics.rst, source/operation/vm_management/vm_instances.rst
=> F #~: Hot resize in vCenter

source/deployment/sunstone_setup/sunstone.rst
=> M #~: Add '/fireedge' to fireedge URL's

source/deployment/sunstone_setup/sunstone.rst
=> F OpenNebula/one#3951: Fix Fireedge connections

source/deployment/vmware_infrastructure_setup/vcenter_setup.rst, source/intro_release_notes/release_notes/whats_new.rst
=> F #4386: import nic alias in vCenter

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#4967: delete services

source/intro_release_notes/upgrades/upgrading_single.rst
To be merged into
- one-5.12
(not master!)
=> F #5217: Fix opennebula-node.deb package name on 5.12

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#5066: Registration time service instance

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#5223: Fix VM tabs not working

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#4994: Add VM name to VNC connection

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#5035: Automatic deletion service

source/intro_release_notes/release_notes/whats_new.rst
=> F #4949: VCENTER_VM_FOLDER per user or group

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#5065: Show state async actions

source/intro_release_notes/release_notes_enterprise/resolved_issues_5128.rst
=> B OpenNebula/one#5220: fix VPCU range

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#649: Enable/Disable Users

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#5162: Update Hosts and VMs datatables columns

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#4039: Numa topology changes for vCenter

source/intro_release_notes/release_notes/whats_new.rst
=> F #5221: sanitize network name in vCenter

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#5209: fix error sched in vm

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#5056: dockerfile sunstone

source/intro_release_notes/release_notes_enterprise/resolved_issues_5128.rst
=> B OpenNebula/one#5212: fix dropdowns on pagination

source/intro_release_notes/release_notes/whats_new.rst
=> B OpenNebula/one#5227: Remove oneflow error on create app dialog

source/configuration_guide/web_interfaces_configuration/suns_views.rst, source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#5011: hide schedule action on VM instantiate

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#5238: overrrides disk inst template

source/configuration_guide/web_interfaces_configuration/suns_views.rst, source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#982: Change boot order on instantiate

source/intro_release_notes/release_notes/whats_new.rst
=> B OpenNebula/one#5200: Fix lock/unlock in Sunstone

source/integration/references/build_deps.rst
=> M #: Add missing build dep on 1604

source/deployment_guide/containerized_deployment/containerized_deployment_reference.rst
=> F OpenNebula/one#5178: Update container deployment

source/intro_release_notes/release_notes/whats_new.rst
=> B OpenNebula/one#5254: Fix Service Update

source/intro_release_notes/release_notes/whats_new.rst
=> B OpenNebula/one#5002: Disable remote actions until monitoring

source/intro_release_notes/release_notes/whats_new.rst
=> B OpenNebula/one#5266: Fix VM warning box blocks other VM tabs

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#4989: Format datablock on creation

source/intro_release_notes/release_notes/whats_new.rst
=> B OpenNebula/One#5288: CPU cost

source/development_guide/system_interfaces/go.rst
=> F OpenNebula/one#4298: Add to documentation

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#5191: Purge DONE services button

source/intro_release_notes/release_notes/whats_new.rst
=> B OpenNebula/One#1501: vm persistent

source/intro_release_notes/release_notes/whats_new.rst
=> F #4933: Support vCenter7

source/open_cluster_deployment/open_cloud_networking_setup/overview.rst
=> M #-: Review Open Cloud Networking Setup Overview

source/installation_and_configuration/opennebula_services/fireedge_configuration.rst
=> F OpenNebula/one#3951: Rroubleshooting FireEdge

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#5280: Iothread id configurable on disks

source/open_cluster_deployment/lxc_node_deployment/lxc_node_installation.rst, source/open_cluster_deployment/open_cloud_networking_setup/node.rst
=> M #-: Review Open Cloud Networking Setup Node

source/intro_release_notes/release_notes/whats_new.rst
=> B OpenNebula/one#5291: Fix VCPU block NUMA sockets

source/installation_and_configuration/opennebula_services/fireedge_configuration.rst
=> M #~: fireedge key information

source/open_cluster_deployment/firecracker_node_deployment/firecracker_driver.rst, source/open_cluster_deployment/lxc_node_deployment/lxc_driver.rst, source/open_cluster_deployment/lxc_node_deployment/overview.rst
Includes:
- overview
- LXC Driver
=> Add LXC docs

source/open_cluster_deployment/open_cloud_networking_setup/bridged.rst
=> M #-: Review Open Cloud Networking Setup Bridged

source/open_cluster_deployment/open_cloud_networking_setup/hm-vlan.rst
=> M #-: Review Open Cloud Networking Setup VLAN

source/open_cluster_deployment/open_cloud_networking_setup/vxlan.rst
=> M #-: Review Open Cloud Networking Setup VXLAN

source/installation_and_configuration/containerized_deployment/custom.rst, source/installation_and_configuration/containerized_deployment/index.rst, source/installation_and_configuration/containerized_deployment/overview.rst
=> F OpenNebula/one#5178: Update container overview

source/locale/es/LC_MESSAGES/administration/references/oned_conf.po, source/locale/es/LC_MESSAGES/integration/cloud_interfaces/occidd.po, source/locale/es/LC_MESSAGES/user/virtual_resource_management/img_guide.po, source/management_and_operations/vm_management/img_guide.rst
Maybe I am missing something. In my eyes that is a typo.
=> M #-: Replace "operative system" by "operating system"

source/installation_and_configuration/large-scale_deployment/sunstone_for_large_deployments.rst
=> M #-: Review Sunstone for large deployment

source/intro_release_notes/release_notes/platform_notes.rst
=> F #~: add vCenter Platform Notes

source/integration_and_development/references/sunstone_dev.rst
=> M autorefresh docs

source/installation_and_configuration/frontend_installation/database.rst
Added 'tasks' on line 13 (Back-end based 'tasks'), as it seemed to require a word there. 
Changed 'completeness' on line 22 to 'information'.
=> reviewed text

source/installation_and_configuration/opennebula_services/oneflow.rst
Line 135: 'resp.' is unclear. Regarding?
=> text reviewed

source/intro_release_notes/release_notes/compatibility.rst
applies to master & one-6.0 also
=> M #~: Fix link

source/intro_release_notes/release_notes_enterprise/resolved_issues_601.rst
=> B OpenNebula/one#5323: Fix VNTemplates ARs

source/intro_release_notes/release_notes_enterprise/resolved_issues_601.rst
=> B OpenNebula/one#5326: Suspend and Stop action in power buttons

source/intro_release_notes/release_notes_enterprise/resolved_issues_601.rst
=> B OpenNebula/one#5327: Fix attribute deletion when update secgroup

source/intro_release_notes/release_notes_enterprise/resolved_issues_601.rst
=> B OpenNebula/one#5322: upload image

source/advanced_components/cloud_bursting/intro.rst
Add reference to new Oracle Cloud driver
=> Update cloud bursting intro in 5.12

source/management_and_operations/multivm_service_management/appflow_use_cli.rst
=> B #5123: add note about crop

source/intro_release_notes/release_notes_enterprise/resolved_issues_601.rst
=> B #5347 fix 2fa sunstone-fireedge

source/intro_release_notes/release_notes/known_issues.rst
Also applies to one-6.0-maintenance.
=> B #: add auth error to known issues

source/intro_release_notes/release_notes_enterprise/resolved_issues_602.rst
=> B #5340: Fix start time on services without registration time

source/intro_release_notes/release_notes_enterprise/resolved_issues_602.rst
=> F #5363: Allow remote connections on Cloud View

source/installation_and_configuration/opennebula_services/sunstone.rst, source/intro_release_notes/release_notes_enterprise/resolved_issues_602.rst
=> B OpenNebula/one#5371: added warning service tab

source/intro_release_notes/release_notes_enterprise/resolved_issues_602.rst
=> B OpenNebula/one#5371: add url issue

source/quick_start/usage_basics/running_kubernetes_clusters.rst
=> M #-: Update Kubernetes Appliance Quick Start

source/intro_release_notes/upgrades/upgrading_single.rst
=> M #-: Point out no CIDR needed

source/intro_release_notes/release_notes_enterprise/resolved_issues_602.rst
=> B OpenNebula/one#5402: Fix Cloud View remote connections options

source/intro_release_notes/release_notes_enterprise/resolved_issues_602.rst
=> B #5403: Fix Cloud view remote connections url

source/intro_release_notes/release_notes_enterprise/resolved_issues_602.rst
=> B OpenNebula/one#5405: redirect flow delete

source/intro_release_notes/release_notes_enterprise/resolved_issues_602.rst
=> B OpenNebula/one#5408: Fix available remote connections

source/integration_and_development/references/build_deps.rst
Merge to master and one-6.0-maintenance
=> B OpenNebula/one#5378: Fix required g++ version

source/installation_and_configuration/containerized_deployment/architecture_deployment.rst, source/intro_release_notes/release_notes_community/resolved_issues_6002.rst
=> M #-: Update platforms, container tags

source/intro_release_notes/release_notes_enterprise/resolved_issues_603.rst
=> B #5393: Add delete this file to vv file

source/intro_release_notes/release_notes/whats_new.rst
=> M #~: Check spell in whatsnew

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#5398: Add feature to whatsnew

source/installation_and_configuration/data_center_federation/config.rst
=> F OpenNebula/One#3959: federation services

source/installation_and_configuration/data_center_federation/config.rst, source/intro_release_notes/release_notes_enterprise/resolved_issues_603.rst
=> B 5395: OneFlow federation in Sunstone

source/intro_release_notes/release_notes_enterprise/resolved_issues_603.rst
=> B OpenNebula/one#5416: fix RDP button in roles VMs not working

source/intro_release_notes/release_notes_enterprise/resolved_issues_603.rst
=> B OpenNebula/One#5415: fix error optional attrs

source/intro_release_notes/release_notes_enterprise/resolved_issues_603.rst
=> B OpenNebula/One#5317: update files in VM context

source/intro_release_notes/release_notes_enterprise/resolved_issues_603.rst
=> F OpenNebula/one#4654: Remove/Add new roles on services

source/intro_release_notes/release_notes_enterprise/resolved_issues_603.rst
=> F OpenNebula/one#5411: Add DockerRegistry marketplace option

source/management_and_operations/vm_management/vm_instances.rst
=> B OpenNebula/one#5393: Note about SPICE, NAT and remote-viewer

source/intro_release_notes/release_notes_enterprise/resolved_issues_603.rst
=> B OpenNebula/one#5420: Fix real CPU & MEM bars on ESX host table

source/intro_release_notes/release_notes_enterprise/resolved_issues_603.rst
=> F OpenNebula/one#5410: Enable and disable marketplaces

source/intro_release_notes/release_notes_enterprise/resolved_issues_603.rst
=> B OpenNebula/one#5122: Fix change token

source/quick_start/operation_basics/provisioning_edge_cluster.rst
=> M #: Fireedge credential notes

source/intro_release_notes/release_notes_enterprise/resolved_issues_603.rst
=> B OpenNebula/one#IPv6 alias not shown in Sunstone

source/intro_release_notes/release_notes_enterprise/resolved_issues_603.rst
=> B OpenNebula/one#5419: fix GUI in fedora

source/intro_release_notes/release_notes_enterprise/resolved_issues_603.rst
=> B OpenNebula/one#5427: disks vm instantiate

source/intro_release_notes/release_notes_enterprise/resolved_issues_603.rst
=> B OpenNebula/one#5432: fix create img error un vCenter view

source/intro_release_notes/release_notes/known_issues.rst
=> B OpenNebula/one#5432: Fix create image error in vCenter view

source/installation_and_configuration/frontend_installation/install.rst, source/installation_and_configuration/opennebula_services/sunstone.rst, source/integration_and_development/references/sunstone_dev.rst, source/intro_release_notes/release_notes/whats_new.rst, source/intro_release_notes/release_notes_community/resolved_issues_6003.rst, source/intro_release_notes/release_notes_enterprise/resolved_issues_603.rst
=> B OpenNebula/one#5434: Disable autorefresh

source/intro_release_notes/release_notes_enterprise/resolved_issues_603.rst
=> B OpenNebula/one#5436: Fix schedule actions weekdays translation

source/management_and_operations/vm_management/vm_instances.rst
Merge to one-6.0-maintenance and master
=> B #OpenNebula/one#5436: Update sched action ranges

source/intro_release_notes/release_notes_enterprise/resolved_issues_603.rst
=> F OpenNebula/one#4661: Update resolved issues

source/intro_release_notes/release_notes_enterprise/resolved_issues_603.rst
=> B OpenNebula/one#5428: Fix OpenNebula versions

source/operation/vm_management/vm_instances.rst
=> M #-: VM snapshots are not lost on suspend/migrate

source/intro_release_notes/release_notes_enterprise/resolved_issues_603.rst
=> B OpenNebula/one#5438: Fix IP shown on Sunstone

source/installation_and_configuration/opennebula_services/fireedge.rst
=> M #-: XMLRPC FireEdge note

source/locale/es/LC_MESSAGES/user/references/template.po, source/management_and_operations/host_cluster_management/hosts.rst, source/management_and_operations/references/template.rst
=> M #-: Update host attribute

source/intro_release_notes/release_notes/compatibility.rst, source/operation/host_cluster_management/host_guide.rst, source/operation/references/template.rst
=> M #: Update compatibility guide

source/management_and_operations/network_management/manage_vnets.rst
=> M #-: SG on NIC_ALIAS important note

source/installation_and_configuration/containerized_deployment/architecture_deployment.rst
To `one-6.0` and `one-6.0-maintenance`
=> M #-: Fix docker compose CE archive version

source/management_and_operations/vm_management/vm_instances.rst
applies to master & one-5.12-maintenance also
=> M #~: Fix typo

source/quick_start/usage_basics/running_kubernetes_clusters.rst
-> master
-> one-6.0-maintenance
=> F #~: add vCenter in Kubernetes doc

source/installation_and_configuration/private_marketplaces/market_s3.rst
=> F #~: add aws to market s3 config

source/intro_release_notes/release_notes_enterprise/resolved_issues_604.rst
=> B OpenNebula/one#5481: fix instantiate vm

source/intro_release_notes/release_notes_enterprise/resolved_issues_604.rst
=> B OpenNebula/one#5476: Fix wrong humanize conversion

source/intro_release_notes/release_notes_enterprise/resolved_issues_604.rst
=> B OpenNebula/one#5507: Fix VNC button cloud view

source/intro_release_notes/release_notes_enterprise/resolved_issues_604.rst
=> B OpenNebula/one#5509: Add to resolved issues

source/intro_release_notes/release_notes_enterprise/resolved_issues_604.rst
=> B OpenNebula/one#5512: fix cloud_vm_create attribute behavior

source/intro_release_notes/release_notes_enterprise/resolved_issues_604.rst
Closes OpenNebula/one#5526
Applies to master as well
BTW missing link on an entry in resolved issues at https://github.com/OpenNebula/docs/blob/one-6.0-maintenance/source/intro_release_notes/release_notes_enterprise/resolved_issues_604.rst
=> B OpenNebula/one#5526: Update resolved issues

source/open_cluster_deployment/lxc_node/lxc_driver.rst
=> F OpenNebula/one/#5506 Update current limitations

source/management_and_operations/vm_management/vm_instances.rst
=> M :-: Sched actions updated by onevm update-chart

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#5479: Add sched actions errors in vm info view

source/intro_release_notes/release_notes_enterprise/resolved_issues_604.rst
=> B OpenNebula/one#5452: Fix Oneflow on Sunstone

source/intro_release_notes/release_notes_enterprise/resolved_issues_604.rst
=> B OpenNebula/one#5527: Add Guest MTU attribute

source/intro_release_notes/release_notes_enterprise/resolved_issues_604.rst
Closes https://github.com/OpenNebula/one/issues/5521
=> F OpenNebula/one#5521: update resolved issues

source/intro_release_notes/release_notes_enterprise/resolved_issues_604.rst
=> F OpenNebula/one#5502: update resolved issues

source/quick_start/deployment_basics/try_opennebula_on_vmware.rst
Fix typo. "bei" should be "be"
=> M #-: Fix typo in try_opennebula_on_vmware.rst

source/intro_release_notes/release_notes/whats_new.rst
=> M #~: Add references to documentation

source/intro_release_notes/release_notes_enterprise/resolved_issues_604.rst
=> B OpenNebula/one#5525: Fix VNTemplate AR update

source/vmware_cluster_deployment/vmware_cluster_deployment/vcenter_driver.rst
=> F #5517: option to keep MAC on imported Wild VM NICs

source/intro_release_notes/release_notes_enterprise/resolved_issues_604.rst
=> B OpenNebula/one#5546: Fix Zendesk login

source/intro_release_notes/release_notes/whats_new.rst, source/management_and_operations/edge_cluster_management/equinix_cluster.rst, source/management_and_operations/references/config/playbooks.rst
=> F #5474: rename Packet to Equinix

source/intro_release_notes/release_notes/whats_new.rst
=> B OpenNebula/one#5547: hide VNC cloud view

source/intro_release_notes/release_notes_enterprise/resolved_issues_604.rst
=> B OpenNebula/one#5543: Fix Sunstone deletes disk attributes

source/intro_release_notes/release_notes/whats_new.rst
=> F #5557: Add issue to whats new

source/installation_and_configuration/opennebula_services/fireedge.rst
=> M #~: fireedge doesnt support x509

source/installation_and_configuration/large-scale_deployment/sunstone_for_large_deployments.rst
=> M #-: Disable opennebula-sunstone if web server

source/intro_release_notes/release_notes/whats_new.rst, source/management_and_operations/references/template.rst
Wait for merging of https://github.com/OpenNebula/addon-context-windows/pull/96
=> F OpenNebula/addon-context-linux#86: Windows support

source/intro_release_notes/release_notes_enterprise/resolved_issues_604.rst
=> B OpenNebula/one#5572: Fix schedule actions

source/intro_release_notes/release_notes_enterprise/resolved_issues_604.rst
Merge with https://github.com/OpenNebula/one-ee/pull/1535
Closes OpenNebula/one#5582
=> B #5582: Update resolved issues

source/intro_release_notes/release_notes/platform_notes.rst
Change spelling of Front-End to include the "-"
=> M #-: Update platform_notes.rst

source/intro_release_notes/release_notes/compatibility.rst
Grammatical / spelling updates
=> M #-: Update compatibility.rst

source/intro_release_notes/release_notes_enterprise/resolved_issues_621.rst
=> B OpenNebula/one#5595: autocomplete inputs

source/intro_release_notes/release_notes_enterprise/resolved_issues_621.rst
=> B OpenNebula/one#5598: Fix Xss

source/_templates/thelayout.html
Applies to 5.12, 6.0, 6.2 & master
=> M #-: Fix search box

source/integration_and_development/infrastructure_drivers_development/devel-vmm.rst
Local actions names are documented wrongly, this PR fixes that.
=> B - Fix local actions names

source/installation_and_configuration/containerized_deployment/reference.rst, source/installation_and_configuration/containerized_deployment/todo/docker_run.txt, source/installation_and_configuration/containerized_deployment/todo/reference.txt, source/installation_and_configuration/containerized_deployment/todo/rests.txt, source/integration_and_development/system_interfaces/java.rst, source/integration_and_development/system_interfaces/ruby.rst, source/management_and_operations/references/config/playbooks.rst, source/management_and_operations/references/config/roles.rst, source/management_and_operations/users_groups_management/accounting.rst, source/management_and_operations/users_groups_management/showback.rst, source/overview/opennebula_concepts/opennebula_overview.rst, source/quick_start/deployment_basics/try_opennebula_on_kvm.rst
=> M #: Add missing bumps

source/installation_and_configuration/frontend_installation/database.rst
=> M #~: Fix comment in MySQL config example

source/intro_release_notes/release_notes_enterprise/resolved_issues_621.rst
=> B OpenNebula/one#5605: Fix role scaling cloud view

source/installation_and_configuration/opennebula_services/oned.rst, source/intro_release_notes/release_notes_enterprise/resolved_issues_621.rst
=> M OpenNebula/one#5431: User encrypted attributes

source/deployment/sunstone_setup/sunstone.rst
=> B #4384: Add documentation about NFS and /var/tmp

source/intro_release_notes/release_notes/whats_new.rst
=> F #5561: Show showback running hours on Sunstone

source/vmware_cluster_deployment/vmware_cluster_deployment/vcenter_driver.rst
-> one-6.2-maintenance
-> master
=> F #5542: add remotedisplay to metadata removed

source/open_cluster_deployment/networking_setup/openvswitch.rst
=> M #-: IP Spoofing for OVS when more than NICs doesn't work

source/intro_release_notes/release_notes_enterprise/resolved_issues_621.rst
=> B OpenNebula/one#5643 Update resolved issues

publish/publish.rb
=> M #-: add debug info to publish script

source/vmware_cluster_deployment/vmware_storage_setup/vcenter_datastores.rst
=> M #: add warning to vCenter MP docs

source/installation_and_configuration/ha/frontend_ha.rst
=> M #-: add note about restart FireEdge in HA

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#5587: Allow charters time modification

source/intro_release_notes/release_notes/known_issues.rst
=> B #5581: Add known issues

source/intro_release_notes/release_notes_enterprise/resolved_issues_621.rst
=> B OpenNebula/one#5534: Fix Sunstone tooltips

source/installation_and_configuration/opennebula_services/sunstone.rst
=> B OpenNebula#5672: remove sentitive data url

source/intro_release_notes/release_notes_enterprise/resolved_issues_621.rst
=> B OpenNebula/One#5672: disable sensitive information

source/management_and_operations/vm_management/vm_instances.rst
This PR applies to: 
- one-6.2
- master
=> B #5590: Fix VMRC keyboard layout

source/installation_and_configuration/whmcs_tenants/configure.rst
Signed-off-by: neal <nhansen@opennebula.io>
=> M #-: Updating WHMCS Documentation to reflect new path

source/intro_release_notes/upgrades/upgrading_federation.rst, source/intro_release_notes/upgrades/upgrading_ha.rst, source/intro_release_notes/upgrades/upgrading_single.rst
=> F OpenNebula/one#5353: Update upgrade process

source/open_cluster_deployment/kvm_node/kvm_driver.rst
Merge to one-6.2-maintanance and master
=> M #-: Note QEMU version for live mem/cpu resize

source/installation_and_configuration/opennebula_services/scheduler.rst
Merge to one-6.2-maintanance and master
=> B OpenNebula/one#5157: Sched DS policies works only for shared DS

source/installation_and_configuration/opennebula_services/oned.rst, source/intro_release_notes/release_notes/whats_new.rst
Created on top of https://github.com/OpenNebula/docs/pull/2070
Should I add something to compatibility section?
=>  F OpenNebula/one#5661: Describe SNAPSHOT_DISK_SIZE_FACTOR 

source/intro_release_notes/release_notes_enterprise/resolved_issues_621.rst
=> B OpenNebula/One#5679: fix warning message

source/intro_release_notes/release_notes_enterprise/resolved_issues_621.rst
-> master
-> one-6.2-maintenance
=> B #5545: fix issue in vCenter VNETs with dpg

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#5568: Add new IP conf method attributes

source/management_and_operations/references/template.rst
=> M #~: Fix to documentation VM Template context note

source/intro_release_notes/release_notes_enterprise/resolved_issues_621.rst
=> B OpenNebula/one#5691: Fix services role display

source/intro_release_notes/release_notes_enterprise/resolved_issues_621.rst
=> B OpenNebula/One#5693: allow sched action

source/intro_release_notes/upgrades/upgrading_ha.rst
This should apply to all versions which are possible to upgrade an HA install
Signed-off-by: root <nhansen@opennebula.io>
=> M #-: Adding clarification to the HA Upgrades process

publish/publish.rb
=> M #-: cleanup old builds

source/installation_and_configuration/frontend_installation/install.rst
applies to `master`, `one-6.2` and `one-6.2-maintenance`
=> M #~: Add ubuntu 18.04 for 3rd dependencies

source/intro_release_notes/release_notes_enterprise/resolved_issues_621.rst
=> B OpenNebula/one#5641: Extend LXC and hide sections

source/intro_release_notes/release_notes_enterprise/resolved_issues_621.rst
=> F OpenNebula/One#5703: fix fireedge REST API

source/management_and_operations/capacity_planning/scheduling.rst
=> M #-: Fix NIC sched_requirements

source/intro_release_notes/release_notes_enterprise/resolved_issues_621.rst
=> B OpenNebula/one#5696: Fix error updating VM Template

source/intro_release_notes/release_notes_enterprise/resolved_issues_621.rst
=> B OpenNebula/one#5714: Fix registration and start time

source/intro_release_notes/release_notes_enterprise/resolved_issues_621.rst
=> B OpenNebula/docs#5712: Update release notes

source/intro_release_notes/release_notes_enterprise/resolved_issues_621.rst
=> B OpenNebula/one#5716: Update release notes

source/intro_release_notes/release_notes_enterprise/resolved_issues_621.rst
=> B OpenNebula/one#5176: Fix updateconf in cloud view

source/intro_release_notes/release_notes_enterprise/resolved_issues_51212.rst
=> B OpenNebula/one#5720: Fix for Sunstone error popup

source/intro_release_notes/release_notes_enterprise/resolved_issues_621.rst
=> B OpenNebula/one#5698: mapping system.config

source/intro_release_notes/release_notes_enterprise/resolved_issues_51212.rst
=> B OpenNebula/one#5238: Sunstone not to override templates

source/intro_release_notes/release_notes_enterprise/resolved_issues_51212.rst
=> B OpenNebula/one#5156: Fix memcache-dalli server

source/intro_release_notes/release_notes_enterprise/resolved_issues_622.rst
=> B OpenNebula/one#5730: Fix cookie expire time

source/installation_and_configuration/opennebula_services/sunstone.rst
=> F OpenNebula/one#1510: Add image path

source/intro_release_notes/release_notes_enterprise/resolved_issues_622.rst
=> F OpenNebula/one#5735: vCenter import filtering and ordering

source/intro_release_notes/release_notes_enterprise/resolved_issues_622.rst
=> F OpenNebula/one#5744: Display scheduler error message

source/intro_release_notes/release_notes_enterprise/resolved_issues_622.rst
=> F OpenNebula/one#5745: present error information in Sunstone

source/intro_release_notes/release_notes_enterprise/resolved_issues_622.rst
=> F OpenNebula/One#5625: download marketapp

source/intro_release_notes/release_notes_enterprise/resolved_issues_622.rst
=> B OpenNebula/one#5736: Import resources only from local zone

source/open_cluster_deployment/kvm_node/kvm_driver.rst
Merge to one-6.2-maintenance and master
=> F #5753: Remove memory_slots from kvm docs

source/intro_release_notes/release_notes_community/platform_notes_620.rst
=> B OpenNebula/one#5754: Note about qemu-img ver

source/intro_release_notes/release_notes_enterprise/resolved_issues_622.rst
=> B OpenNebula/one#5560: Fix disk size not showing correctly

source/management_and_operations/edge_cluster_management/aws_cluster.rst
=> M #-: fix typo

source/intro_release_notes/release_notes_enterprise/resolved_issues_622.rst
=> B OpenNebula/one#5771: Fix disk size sliders

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/one#5760: Add option to hide VM naming

source/installation_and_configuration/opennebula_services/fireedge.rst
=> M #~: remove fireedge.error file

source/management_and_operations/edge_cluster_management/cluster_operations.rst
For me the `make html` command gives error. Which is fixed by this commit.
I'm surprised nobody noticed this, maybe the error can be solved also by some configuration of the sphinx, which I'm missing?
Merge only to master
=> M #-: Fix build of the docs

source/open_cluster_deployment/lxc_node/lxc_node_installation.rst, source/open_cluster_deployment/storage_setup/ceph_ds.rst
Applies to 6.2 and 6.0, maintenance and non-maintenance versions as well.
=> M #: Add LXC Ceph dependency

source/intro_release_notes/release_notes/known_issues.rst, source/intro_release_notes/release_notes_enterprise/resolved_issues_621.rst
Merge to one-6.2
Maybe merge also to one-6.2-maintanance?
=> M #-: Fix wrong links

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/One#5779: SSO

source/vmware_cluster_deployment/vmware_cluster_deployment/vcenter_driver.rst
=> M #-: Adding sparse_images description to vcenter driver tuning

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/One#5786: add localStorage in fireedge

source/intro_release_notes/release_notes/known_issues.rst
=> M #-: Update known_issues.rst

source/open_cluster_deployment/lxc_node/lxc_driver.rst
Applies to 6.2 and 6.2 maintenance as well
=> M #: XFS 4K warning

source/intro_release_notes/release_notes/known_issues.rst
Applies to 6.2 and 6.2-maintenance as well.
=> B OpenNebula/one#5802: Add known issues

source/intro_release_notes/release_notes/compatibility.rst, source/open_cluster_deployment/kvm_node/kvm_driver.rst
Applies to 5.12+
Closes OpenNebula/one#5680
=> B OpenNebula/one#5680: Update KVM parallel actions

source/integration_and_development/references/fireedge_sunstone_dev.rst, source/management_and_operations/vm_management/fireedge_sunstone.rst
=> M #~: Add FireEdge Sunstone docs

source/intro_release_notes/release_notes/whats_new.rst
=> B OpenNebula/one#5810: Update resovled issues

source/management_and_operations/vm_management/fireedge_sunstone.rst
=> M #~: Add new FireEdge Sunstone user settings

source/management_and_operations/vm_management/fireedge_sunstone.rst
=> F #5422: Unify usage section on FireEdge Sunstone

source/intro_release_notes/release_notes/known_issues.rst, source/intro_release_notes/release_notes/whats_new.rst, source/management_and_operations/references/creating_images.rst, source/management_and_operations/references/install_steps.txt, source/management_and_operations/references/template.rst
=> M #-: Update contextualization in 6.4

source/intro_release_notes/release_notes/platform_notes.rst
=> M #-: Update supported context. guests in 6.4
