source/integration/infrastructure_integration/devel-im.rst, source/locale/es/LC_MESSAGES/integration/infrastructure_integration/devel-im.po
Hi, 
while reading through http://docs.opennebula.org/4.12/integration/infrastructure_integration/devel-im.html i noticed a small typo "diver" vs "driver". This pull-request fixes that.
Best wishes,
Matthias
=> Fix minor typo (diver vs. driver)

source/administration/storage/ceph_ds.rst
CEPH_HOST should be part of the example file, I believe it is required.
=> example ds.conf does not have CEPH_HOST entry, which is required

source/administration/storage/ceph_ds.rst
It appears the command:
ceph auth get client.libvirt -o ceph.client.libvirt.keyring (line 152)
creates the file ceph.client.libvirt.keyring
however later in the documentation it refers to that file as client.libvirt.keyring so I renamed to ceph.ceph.client.libvirt.keyring to keep it consistent.
=> file name was not consistent

source/administration/virtualization/kvmg.rst
Add missing cgroup configuration for libvirt. 
There are some additional cgroups that are needed by libvirt to start a VM when configured. Added in cgconfig.conf to mount them too.
The missing pieces are partially mentioned below in the docs.
=> improve libvirt configuration for cgroups

source/integration/system_interfaces/api.rst
Docs stated the operation 'one.vm.disksave' existed. The real name is 'one.vm.disksaveas'
=> Fix inconsistency between XMLRPC operation and docs

source/administration/storage/iscsi_ds.rst
Hi,
I've added a section titled "Further notes on Installation and Usage" in the file iscsi_ds.rst. This section documents how to install iSCSI datastore support on Ubuntu-based KVM hypervisors and also documents some examples of the datastore use.
Thanks,
=> Clarification on iSCSI datastore documentation

source/deployment/opennebula_installation/frontend_installation.rst
Systemd has been adopted as the default init system for most of OpenNebula's certified Front-end components (CentOS 7, Debian 8 and Ubuntu 16.04) so systemctl should be added. In the future the service command could be removed.
=> Add systemctl to Step 6

source/deployment/node_installation/kvm_node_installation.rst
As stated in https://forum.opennebula.org/t/scp-r-need-password-why/3055/2 in some OpenNebula's operations like clone, scp uses the frontend as the source of the command. In order to avoid key host verification errors, the frontend should be added to the ssh-keyscan command and an ssh connection from the frontend against the frontend itself should be added to the verification steps.
=> Add frontend to ssh verification

source/advanced_components/application_insight/onegate_configure.rst
Systemctl is now the default service management tool for many Linux distros
=> Add systemctl for onegate server management

source/integration/system_interfaces/api.rst
As discussed in https://forum.opennebula.org/t/issue-in-vmpool-showback-method-in-xml-rpc-integration-api-opennebula-5-0-2/3226 it seems that filter input was missing in docs.
=> Add missing filter flag parameter to showback

source/operation/vm_setup/add_content.rst
New 5.3.80 one-context "provides" cloud-init (not a big fan, but whatever...)
So installing new 5.3.80 one-context with previous instructions sort-of updates cloud-init package, which is then removed, removing one-context.
It's safe for old and new one-context package to first remove cloud-init and then install one-context
(i have no clue if this is relevant for other OSes)
=> Delete cloud-init before installing one-context

source/deployment/authentication_setup/ldap.rst
`simple_tls` isn't a supported authentication method.
=> Remove simple_tls from LDAP auth_method

source/advanced_components/ha/frontend_ha_setup.rst
Update the follower hook to the actual file just to make sure that somebody working by the docu does not blindly copy the wrong script and ends up with all nodes having the leader IP.
=> Updated Follower hook script name

README.md
I think that the ONE doc project use the sphinx_rtd_theme and not the sphinx_bootstrap_theme
=> update sphinx theme

source/deployment/opennebula_installation/frontend_installation.rst
The RHEL 7 EPEL repo requires a link to the official instructions. I also made the documentation a little more readable.
=> Updated the RHEL 7 server instructions

source/deployment/node_installation/kvm_node_installation.rst
This updates the command to restart libvirtd from `service` to `systemctl`. While invoking `service` will still work, it is depreciated.
=> Change service command to systemctl.

source/deployment/node_installation/kvm_node_installation.rst
When you follow the docs step-by-step, and do not run apt-get update after adding the repositories, you risk installing the OS-variant of opennebula-node, and not the one from the repository that was just added.
=> Apt-get updated needed after adding repositories

source/deployment/vmware_infrastructure_setup/datastore_setup.rst
Related to [this issue](https://github.com/OpenNebula/one/issues/2437).
We aim for relase 5.6.2 and we still have to perform some testing actions so we need to wait for 5.6.1 and the proper merge of this [PR](https://github.com/OpenNebula/one/pull/2425).
Also we should add this to the next resolved issues for 5.6.2
=> B #2420: removed line about vCenter image requirements

source/deployment/opennebula_installation/frontend_installation.rst
To be merged into `one-5.6`.
If possible, cherry-pick also into:
- `one-5.4`
- `one-5.2`
- `one-5.0`
=> B #2778: Bundler 2.0.x requires Ruby 2.3+

source/deployment/node_installation/lxd_node_installation.rst
Just a note that LXD package is always installed on Ubuntu LTS, when the other option is not specified. And, note to handle carefully installations if the LXD is already installed and used.
To be applied into
- merge into one-5.8 (not maintenance)
- cherry-pick into master
=> F OpenNebula/packages#65: Note preferred LXD pkg

source/deployment/open_cloud_host_setup/kvm_driver.rst
=> M #: doc required one restart

source/deployment/authentication_setup/ldap.rst
implemented in OpenNebula/one#3379
=> M #: document new :group_base ldap config

source/deployment/node_installation/vcenter_node_installation.rst
Modified vCenter node installation documentation to add
necessary priviledges to be able to do migrations.
Sort list alphabetically
=> B #3274: Added permission in doc to DS migration

source/integration/references/compile.rst, source/intro_release_notes/release_notes/whats_new.rst
Applies only for master
Updated docu with:
- the last requirements (remove deprecated, updated LXD)
- the generator
- removed the cat warning since the code actually needs the `catfstab` command
=> B OpenNebula/one#3046: Review sudoers

source/deployment/sunstone_setup/suns_auth.rst
Recommend the user to pass Forwarded-For and Forwarded-Proto scheme to let Sinatra know what the URL scheme requested is. 
The URL scheme is useful so Sunstone can potentially set cookies with a Secure flag.
It's also potentially useful (in the future?) to let Sinatra know what the real request address is, so I've included that.
=> Pass scheme to support Secure cookies in sunstone

source/deployment/repositories.txt
Avoid $basearch shell expansion by quoting heredoc.
=> Remove shell expansion in repositories.txt

source/deployment/cloud_design/open_cloud_architecture.rst
Missing header
Applicable also to 5.8 and 5.10
=> M #: Fix line end

source/deployment/open_cloud_host_setup/kvm_driver.rst
Requires cherry-pick to: one-5.10, one-5.10-maintenance
Signed-off-by: Ricardo Diaz <rdiaz@opennebula.systems>
=> M-#: Incorrect disk dev prefixes for virtio

source/deployment/node_installation/kvm_node_installation.rst, source/deployment/opennebula_installation/frontend_installation.rst, source/intro_release_notes/release_notes/whats_new.rst
- add the notice about the new SSH agent method vs the old
- adjust the instructions to describe the default SSH agent way
=> F Opennebula/one#2152: Update passwordless login

source/deployment/node_installation/fc_node_installation.rst, source/deployment/node_installation/kvm_node_installation.rst, source/deployment/opennebula_installation/epel.txt, source/deployment/opennebula_installation/frontend_installation.rst, source/deployment/opennebula_installation/repositories.rst, source/operation/network_management/vrouter.rst
Multiple updates:
- update for custom `gem install` for newer Ruby gems (e.g., C8)
- configure EPEL on nodes
- document how to store enterprise credentials in seperate file (D10+, Ubuntu 16.04+)
- reference new VNF in VR
Applies to one-5.12 and master.
=> M #-: Updates to repos, gem install, VNF

source/deployment/sunstone_setup/sunstone.rst, source/integration/references/sunstone_dev.rst, source/intro_release_notes/release_notes_community/whats_new.rst
=> F OpenNebula/one#2410: VM autorefresh

source/deployment/open_cloud_host_setup/lxd_driver.rst, source/operation/references/template.rst
Applies to:
- master
- 5.12
- 5.10
- 5.8
=> M #: Update LXD raw attr docu

source/deployment/open_cloud_host_setup/kvm_driver.rst, source/deployment/sunstone_setup/sunstone.rst, source/operation/vm_management/vm_instances.rst
It is impossible to generate PDF documentation with LaTeX, because some codes (few looks like unicode and few are suspicious) causes LaTeX to bail-out with errors like:
```
! Package inputenc Error: Unicode character ​ (U+200B)
(inputenc)                not set up for use with LaTeX.
See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
...
l.8695 ...also override these SPICE parameters ​
```
This PR removes these codes which fixes PDF generation in my environment.
How to reproduce - tested on Debian10:
```shell
sudo apt-get install git make python3-sphinx-rtd-theme \
python3-yaml python3-dev python3-pip 
sudo pip3 install sphinx-prompt
mkdir ~/projects
cd ~/projects
git clone https://github.com/OpenNebula/docs.git
cd docs/
git describe --long …
```
=> M #-: Remove LaTeX incompatible codes

source/deployment/opennebula_installation/mysql_setup.rst
Running MySQL version 8 here, the instructions for GRANT ALL PRIVILEGES are for MySQL 5.7. Contributing to help update the setup guide.
=> Minor update for MySQL version 8

source/intro_release_notes/release_notes_enterprise/resolved_issues_603.rst
=> B OpenNebula/one#2187: Fix IPv6 size not required with no-SLAAC

source/intro_release_notes/release_notes_community/resolved_issues_6003.rst, source/intro_release_notes/release_notes_enterprise/resolved_issues_603.rst
=> B #5437: PyONE strips white-spaces in VM attribute

source/intro_release_notes/release_notes_enterprise/resolved_issues_621.rst
=> B OpenNebula/one#5651: Fix VMTemplate lock and unlock

source/intro_release_notes/release_notes_enterprise/resolved_issues_51211.rst
=> B OpenNebula/one#5650: Hide SSH configurations on settings.ssh_key false

source/intro_release_notes/release_notes_enterprise/resolved_issues_621.rst
=> B OpenNebula/one#5650: Hide SSH configuration on settings.ssh_key false 

source/intro_release_notes/release_notes_enterprise/resolved_issues_51211.rst
The issue has been backported, adding to resolved issues
Merge to one-5.12-maintanance and one-5.12
=> B OpenNebula/one#5196: Update resolved issues

source/intro_release_notes/release_notes_enterprise/resolved_issues_621.rst
=> B #5370: fix names with | char cannot be imported from vCenter

source/management_and_operations/capacity_planning/quotas.rst
DATASTORE has attribute IMAGES, not IMAGE.
=> quotas.rst: IMAGES, not IMAGE in DATASTORE

source/quick_start/usage_basics/overview.rst
Just a tiny typo in the page: `virutal` instead of `virtual`.
And as an added bonus, I added a comma for a better punctuation :smile: .
=> Fixing typo in overview page.

source/intro_release_notes/release_notes_enterprise/resolved_issues_51212.rst
=> B OpenNeubla/one#5701: Show external IPs on VM datatable

source/intro_release_notes/release_notes_enterprise/resolved_issues_621.rst
=> B OpenNebula/one#5707: Hide remote console options not available

source/intro_release_notes/release_notes/whats_new.rst, source/open_cluster_deployment/lxc_node/lxc_driver.rst
Closes OpenNebula/one#5429
Template reference was already specifying the usage of TARGET from migrating the LXD driver documentation.
=> F OpenNebula/one#5429: feature documentation

source/installation_and_configuration/frontend_installation/database.rst, source/installation_and_configuration/frontend_installation/install.rst, source/installation_and_configuration/frontend_installation/opennebula_repository_configuration.rst, source/installation_and_configuration/opennebula_services/sunstone.rst, source/integration_and_development/references/build_deps.rst, source/intro_release_notes/release_notes_enterprise/platform_notes_621.rst, source/intro_release_notes/upgrades/upgrading_single.rst, source/management_and_operations/edge_cluster_management/onprem_cluster.rst, source/management_and_operations/end-user_web_interfaces/sunstone_labels.rst, source/management_and_operations/references/config/roles.rst, source/open_cluster_deployment/firecracker_node/firecracker_node_installation.rst, source/open_cluster_deployment/kvm_node/kvm_node_installation.rst, source/open_cluster_deployment/lxc_node/lxc_node_installation.rst, source/quick_start/usage_basics/running_containers.rst
I consider the time between 6.2.1 EE and first CE release transitional, so at some places related solely to CE I left CentOS mentioned.
Where the documentation is general (no CE/EE mentioned) and where it is related to the supported OS, there I removed CentOS.
I still left it only there where it's used as an image example and also in MiniONE/oneprovision docs where update is pending.
=> Remove replace CentOS where appropriate

source/intro_release_notes/release_notes_enterprise/resolved_issues_622.rst
=> B OpenNebula/one#5451: Clean VCPU_MAX and MEMORY_MAX

source/installation_and_configuration/frontend_installation/install.rst, source/installation_and_configuration/frontend_installation/opennebula_repository_configuration.rst
Half of the repo links were stills et to 6.2, this updates those to 6.4 as well as the explanation of subversions note.
This appears to apply to branch one-6.4-maintenance as well
=> Updating some 6.2 references to 6.4.0

source/intro_release_notes/release_notes/compatibility.rst
Cleaning out the 6.2x -> 6.4.x, changing to 6.4.x -> 7.0.x and stating new JSON changes to the database as well as roughly how long a large database can take, and the impact the storage has.
=> F OpenNebula/one#5861: Adding new JSON DB changes

source/intro_release_notes/release_notes_enterprise/resolved_issues_642.rst
Merge only to one-6.4-maintanance
Ads `CONTEXT_RESTRICTED_DIRS` to backported issues
=> M #-: Add context_restricted_dirs to backported issues

source/installation_and_configuration/opennebula_services/oned.rst, source/management_and_operations/references/template.rst
Merge to master and one-6.4-maintanance
By default restricted dirs contains only `/etc`, so I think we don't need to add this to compatibility guide
=> M #-: context restricted dirs documentation

source/integration_and_development/references/build_deps.rst
scons fails to execute because of the missing package on the dependency list.
Applies as well to
- master
- one-6.4 non-maintenance
=> M #: Add missing build dep

source/intro_release_notes/release_notes_enterprise/resolved_issues_642.rst
=> B OpenNebula/one#5970: Fix ignore volatile disks

source/intro_release_notes/release_notes/whats_new.rst, source/management_and_operations/storage_management/datastores.rst
Attribute `CONTEXT_DISK_TYPE` added to datastore attributes in the datastore documentation.
=> F OpenNebula/one#5681: Doc for block context devices

source/intro_release_notes/upgrades/upgrading_federation.rst
Clarifying the onedb usage when upgrading a federated cloud to include a message about MySQL or PostgreSQL usage, and a link to the page detailing these CLI commands.
=> M #-: adding note about mysql/pgsql for onedb

source/installation_and_configuration/large-scale_deployment/sunstone_for_large_deployments.rst
- master
- one-6.6
- one-6.4
- one-6.2: This is to have the previous documentation without errors
- one-6.2-maintenance: This is to have the previous documentation without errors (IDK if this is needed)
=> M #~: Fix to show nginx configuration example

source/installation_and_configuration/frontend_installation/opennebula_repository_configuration.rst
Can be added to all the versions that support Ubuntu 22.04
- release-6.6.0
- release-6.6.1
- master
=> M #-: Update gpg key repo adding on Ubuntu 22.04

source/installation_and_configuration/opennebula_services/sunstone.rst
Adding a note directly after the fireedge endpoint explanation detailing to set them to `''` to disable them. 
Should apply to all of 6.x
=> M #-: Clarifying how to disable fireedge vnc

source/installation_and_configuration/opennebula_services/support.rst, source/intro_release_notes/release_notes_enterprise/resolved_issues_663.rst
Applies to:
- `one-6.6-maintenance`
- `one-6.4-maintenance`
The Onegather example in the support section has also been updated with the new log output.
=> F OpenNebula/support#56 Update release notes

source/installation_and_configuration/opennebula_services/oned.rst
Clarifies the available values for the ALLOW_ORPHANS attribute for datastores in the documentation.
This should apply to 6.0 and up.
=> F OpenNebula/one#6267: improve ALLOW_ORPHANS documentation

source/intro_release_notes/release_notes/whats_new.rst, source/management_and_operations/end-user_web_interfaces/fireedge_sunstone.rst
=> F OpenNebula/One#6123: add VDC tab

source/intro_release_notes/release_notes/whats_new.rst
=> F OpenNebula/One#6211: Fix datastore ignores cluster id

source/open_cluster_deployment/kvm_node/pci_passthrough.rst
Some clients had problems with the device permissions for PCI passthrough. This adds a note to set them up with a udev rule
=> M #-: Add udev rule for PCI passthrough permission

source/intro_release_notes/release_notes/whats_new.rst, source/management_and_operations/end-user_web_interfaces/fireedge_sunstone.rst
Adds the OpenNebula/one#6121 user's tab feature to the [whats new](https://github.com/OpenNebula/docs/blob/master/source/intro_release_notes/release_notes/whats_new.rst) and [web management and operations](https://github.com/OpenNebula/docs/blob/master/source/management_and_operations/end-user_web_interfaces/fireedge_sunstone.rst) sections.
---
* **master**
* OpenNebula/one#6121
=> F OpenNebula/one#6121: Added User tab documentation

source/management_and_operations/references/install_steps.txt
Fixed typo under "Debian/Ubuntu/Devuan" should be "one-context_" instead of "one-context-". Previously it would give 404 Error
=> Fixed typo in install_steps.txt

source/installation_and_configuration/opennebula_services/fireedge.rst
Adds the maintenance release notes for the vm group tab with a link to the additional configuration files...
* **one-6.8-maintenance**
=> M #-: Add vmgroup conf instructions

source/marketplace/public_marketplaces/dockerhub.rst
Applies to everything
- Added missing format URL argument explanation
- Expanded URL image argument for official and unofficial images
- previous example showcased an official image download, but the section in question is for non official images.
=> M #: User dockerhub non official image for non official image download

source/intro_release_notes/release_notes/known_issues.rst
Merge to master and 6.8
I've tested the `onezone serversync` with PostgreSQL and it doesn't throw any error
=> M #-: Remove onezone serversync from known issues

source/intro_release_notes/release_notes/whats_new.rst
"Fix for systemd unit files in the part responsible for log compression" was added to "What's new section"
=> B OpenNebula/one#6282: Update whats_new.rst

source/intro_release_notes/release_notes/known_issues.rst
Adds the vcenter image creation timeout issue to the known isuses for 6.8.1
=> B OpenNebula/one#6431: add vcenter image issue to known issues

source/intro_release_notes/release_notes/known_issues.rst
adds known issue for missing `require` statement in vcenter/stat script
=> B OpenNebula/one#6427: add stat bug to known issues

source/open_cluster_deployment/storage_setup/ceph_ds.rst
Add instructions to create RBD pool
Add instructions to create RBD pool. Without this step, adding RBD pools to Sunstone using `onedatastore create systemds.txt` will lead to zero space capacity in "Datastore menu"
<hr>
=> Add instructions to create RBD pool

source/management_and_operations/storage_management/images.rst
'-n' option added to echo command when adding LUKS passkey to the libvirtd
<hr>
=> M #-: Fix for echo command to add LUKS key properly

source/intro_release_notes/release_notes_enterprise/resolved_issues_682.rst
This PR hides the create vms button when the cloud_vm_create option is set to false
=> B OpenNebula/One#6450: Fix create vm button in clod view

source/intro_release_notes/release_notes_enterprise/resolved_issues_682.rst
this PR resolves the image upload with the directory set in the configuration file and when the request fails, it issues an error message blocking the image allocation request.
=> B OpenNebula/One#6423: fix upload image in fireedge

source/intro_release_notes/release_notes_enterprise/resolved_issues_682.rst
Adding fix for timeout during `oneimage create` with high curl versions to resolved issues
=> B OpenNebula/one#6431: 'oneimage create timeout' resolved issues

source/intro_release_notes/release_notes_enterprise/resolved_issues_682.rst
B Opennebula/one#6379 Fix VM Migration Failure Using Two SYSTEM_DS on same host
<hr>
=> B Opennebula/one#6379 Fix VM Migration Failure Using Two SYSTEM_DS on same host

source/intro_release_notes/release_notes/whats_new.rst
This PR fixes the display of the MEMORY, CPU and VCPU inputs in the VM instantiate form and fixes the order of the options when they are numbers
=> B OpenNebula/One#6229: fix sorting user inputs

source/intro_release_notes/release_notes_enterprise/resolved_issues_682.rst
This PR fixes the display of the MEMORY, CPU and VCPU inputs in the VM instantiate form and fixes the order of the options when they are numbers
=> B OpenNebula/One#6229: fix sort options in user_inputs

source/installation_and_configuration/frontend_installation/opennebula_repository_configuration.rst
- apt-key is warned to be deprecated after Ubuntu 2204
- it's a good practice not to add apt keys inside fully trusted /etc/apt/trusted path but rather /usr/share/keyrings and reffer them per apt repo
=> B #OpenNebula/6428: Replace deprecated apt-key

source/installation_and_configuration/frontend_installation/opennebula_repository_configuration.rst
Changed all echo into apt sources lines to be signed, not singed
I used copy and paste to setup my repo config on Ubuntu 22.04 but hitting GPG signing errors. There is a typo in all the entries. 
- [X ] master
<hr>
=> Update opennebula_repository_configuration.rst : Typo in sources configuration

source/intro_release_notes/release_notes_enterprise/resolved_issues_682.rst
This PR adds user settings in the "Setting" tab, adjusts the where some fireedge settings are saved in the user template, copy to clipboard functionality
<hr>
=> B OpenNebula/One#6219: add generic template settings

source/installation_and_configuration/opennebula_services/fireedge.rst, source/intro_release_notes/release_notes_enterprise/resolved_issues_682.rst
Update 6.8.2 config download link for FireEdge + change from [DownGit](https://minhaskamal.github.io/DownGit/#/home) to [download-directory](https://download-directory.github.io/) instead. Because for some reason, DownGit sometimes gets flagged as malicious.
<hr>
=> F OpenNebula/one#5687: Update config download link

source/integration_and_development/references/compile.rst
If a set of commands is executed as it is listed now in the [guide](https://docs.opennebula.io/6.8/integration_and_development/references/compile.html#) i.e.
```
oneadmin@frontend:~/ $> wget <opennebula tar gz>
oneadmin@frontend:~/ $> tar xzf <opennebula tar gz>
oneadmin@frontend:~/ $> cd opennebula-x.y.z
oneadmin@frontend:~/opennebula-x.y.z/ $> scons -j2 mysql=yes syslog=yes
[ lots of compiling information ]
scons: done building targets.
oneadmin@frontend:~/opennebula-x.y.z $> sudo ./install.sh -u oneadmin -g oneadmin
```
the following error appears:
```
cp: cannot stat '/home/pablo/Documents/OpenNebula/opennebula-6.8.0/src/fireedge/dist': No such file or directory
cp: cannot stat '/home/pablo/Documents/OpenNebula/opennebula-6.8.0/src/fireedge/node_modules': No such file or directory
``` …
=> M #-: Add fireedge=yes to scons command

source/intro_release_notes/release_notes_enterprise/resolved_issues_682.rst
Fix wrong link for "Fix PCI passthrough device addresses for machine models based on q35" in Resolved issues
=> M #-: Fix wrong link in Resolved issues

source/intro_release_notes/release_notes_enterprise/resolved_issues_683.rst
New bug fix added to the list of resovled issues. The exit code of the CLI tools now is coherent when using the --json and --yaml options. 
<hr>
=> B #6509: Fix error reporting of CLI tools for JSON and YAML output

source/intro_release_notes/release_notes_enterprise/resolved_issues_646.rst
New bug fix added to the list of resovled issues. The exit code of the CLI tools now is coherent when using the --json and --yaml options. 
<hr>
=> B OpenNebula/one#6509: Fix error reporting of CLI tools for JSON and YAML output

source/intro_release_notes/release_notes_enterprise/resolved_issues_683.rst
This pull request updates the 6.8.3 release notes to include the resolution of issue #6511, which fixes the CLI listing formatting when using the --search option.
<hr>
=> Added resolved issue #6511 to 6.8.3 release notes.

source/intro_release_notes/release_notes_enterprise/resolved_issues_646.rst
This pull request updates the 6.4.6 release notes to include the resolution of issue #6511, which fixes the CLI listing formatting when using the --search option.
<hr>
=> Added resolved issue #6511 to 6.4.6 release notes.

source/provision_clusters/references/playbooks.rst, source/provision_clusters/references/roles.rst
Refactor:
* Edge and Cloud Providers
* Edge Cluster Provisions
* HCI Cluster Provisions
* Operations
<hr>
=> F OpenNebula/one#6430: Refactor providers section

source/installation_and_configuration/opennebula_services/oneflow.rst, source/integration_and_development/system_interfaces/appflow_api.rst
Refactor:
* XML-RPC API
* Ruby OpenNebula Cloud API
* Python OpenNebul Cloud API
* Java OpenNebula Cloud API
* Go OpenNebula Cloud API
* OneFlow Server API
* OneGate API
* Using Hooks
<hr>
=> F OpenNebula/one#6430: Refactor API section

source/intro_release_notes/release_notes/whats_new.rst, source/management_and_operations/backups/index.rst, source/management_and_operations/backups/overview.rst, source/management_and_operations/backups/restic.rst, source/management_and_operations/capacity_planning/quotas.rst, source/management_and_operations/monitor_alert/index.rst, source/management_and_operations/monitor_alert/install.rst, source/management_and_operations/monitor_alert/overview.rst
Modified RN What's New and other files to reflect that Prometheus and Restic are now included in CE
<hr>
=> M #-: 6.10 Prometheus and Restic in CE

source/ext/spellchecking/wordlists/opennebula.txt
Added "ubuntu" in lowercase to the wordlist since it was causing the spell check to fail, and the word in lowercase will probably pop up again in other docs, in the Version string of packages e.g. 8.0.28-0ubuntu4
<hr>
=> M #-: Add word to spellchecking wordlist

source/index.rst
Adds a table at beginning of the docs index page, linking to Quick Start and Overview sections.
(In this and other PRs spellcheck fails due to type in external file, fixed in https://github.com/OpenNebula/docs/pull/3007.)
<hr>
=> M #-: 6.10 Add short intro to general docs index

source/installation_and_configuration/opennebula_services/monitoring.rst
The mentioning of ``monitord.log`` is replaced with ``monitor.log`` as well as VM_MONITORING_EXPIRATION_TIME attribute and its description are added (for some reasons it was missing in the documentation while presenting in the ``monitord.conf`` file).
Plus few periods are removed at the end of sentences in the tables for sake of consistency. 
<hr>
=> M #-: monitor.log and VM_MONITORING_EXPIRATION_TIME

source/installation_and_configuration/frontend_installation/install.rst
=> M #-: Update provision deps installation

source/installation_and_configuration/opennebula_services/fireedge.rst
According to my test with Fireedge - it looks for a custom logo in the `/usr/lib/one/fireedge/dist/client/assets/images/logos/` direcotry instead of the one mentioned in docs. 
<hr>
=> M #-: change the path to "logos" directory in Fireedge

source/installation_and_configuration/authentication/sunstone_auth.rst
This PR adds Doc to enable the functionality to authenticate using an x509 certificate
<hr>
=> F #6676: add auth x509 in fireedge

source/quick_start/usage_basics/running_kubernetes_clusters.rst
Traefik >= 3 expects `apiVersion: traefik.io/v1alpha1`, this PR fixes the example in OneKE/QS.
<hr>
=> M #-: OneKE/QS: Use correct apiVersion for IngressRoute (fix)

source/installation_and_configuration/frontend_installation/opennebula_repository_configuration.rst
If CRB/powertools is [not enabled](https://github.com/OpenNebula/one-infra/blob/bde4928d80caed984bb422877e850ba7c934888f/microenvs/ansible/roles/opennebula-repository-microenv/tasks/RedHat.yml#L87-L96) then installing opennebula is not possible on rhel variants
```
[root@alma9-247 ~]# yum install opennebula
Last metadata expiration check: 0:00:05 ago on Fri Sep 13 17:22:16 2024.
Error:
Problem: conflicting requests
- nothing provides libmysqlclient.so.21()(64bit) needed by opennebula-6.10.0-1.el9.x86_64 from opennebula
- nothing provides libmysqlclient.so.21(libmysqlclient_21.0)(64bit) needed by opennebula-6.10.0-1.el9.x86_64 from opennebula
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```
<hr>
=> M #: Add required extra repo for rhel family

source/_templates/footer.html
Updated the copyright year in the footer that appears on all docs pages
<hr>
=> M #-: Fix copyright date in documentation footer

source/ext/spellchecking/wordlists/opennebula.txt, source/installation_and_configuration/frontend_installation/opennebula_repository_configuration.rst
A command
```
wget -q -O- https://downloads.opennebula.io/repo/repo2.key | gpg --dearmor --yes --output /etc/apt/keyrings/opennebula.gpg
```
fails on a Debian 11 based hosts because a `/etc/apt/keyrings` directory does not exist by default. So one needs to create it first which is proposed the note about.
<hr>
=> M #-: Add a note for Debian 11 repo

source/quick_start/operation_basics/provisioning_edge_cluster.rst
It looks that we refer here `oneadmin` as a command instead of as an user.
<hr>
=> Fix oneprovision command usage on provisioning_edge_cluster.rst

source/integration_and_development/system_interfaces/appflow_api.rst, source/management_and_operations/multivm_service_management/appflow_use_cli.rst
Fixed a few errors in recent changes: a few indentation errors and misnamed labels that were causing Sphinx to throw errors when building from master.
In some instances, changed `.. code-block:: json` to simply `.. code::` because the code snippets contain ellipses (...) to indicate skipped lines, and Sphinx considers those as errors and highlights them in red in the HTML output. Removing the `json` parameter fixes that, although it disables syntax highlighting in the code block. (The `:force:` option disables the build error messages but still highlights the ellipses in red in the HTML.)
This applies to the `master` branch.
<hr>
=> M #-: Fix some formatting to avoid Sphinx errors on build

source/intro_release_notes/upgrades/upgrading_single.rst
Add clarification on when to manually download `opennebula-migration-community` package
<hr>
=> M #-: Clarify when to manually download CE migration package

source/overview/cloud_architecture_and_design/cloud_architecture_design.rst, source/quick_start/deployment_basics/overview.rst
In "Deployment Basics Overview", added link to Deploying a Front-end On-prem page.
In "Cloud Arch. and Design", modified a link to point to "Deployment Basics Overview" instead of "Deploying on AWS", so readers can see the different deployment possibilities.
<hr>
=> M #-: Add link to installing Front-end onprem

source/management_and_operations/vm_management/vm_instances.rst
When using the [API](https://docs.opennebula.io/6.10/integration_and_development/system_interfaces/api.html#one-vm-migrate) or the CLI
```
onevm migrate --live --help
migrate <range|vmid_list> <hostid> [<datastoreid>]
Migrates the given running VM to another Host. If used with --live
parameter the miration is done without downtime.
States: RUNNING
valid options: enforce, live, poweroff, poweroff_hard
-e, --enforce             Enforce that the host capacity is not exceeded
--live                    Do the action with the VM running
--poff                    Do the migrate by poweringoff the vm
--poff-hard               Do the migrate by poweringoff hard the vm
-v, --verbose             Verbose mode
-h, --help                Show this message
-V, --version             Show version and …
```
=> Clarify live migration limitation

source/management_and_operations/references/template.rst, source/management_and_operations/vm_management/vm_templates.rst
Spelling mistakes in doc about user inputs.
<hr>
=> M #-: Spelling mistakes

source/ext/spellchecking/wordlists/opennebula.txt, source/management_and_operations/vm_management/vm_instances.rst, source/open_cluster_deployment/kvm_node/kvm_driver.rst
* Update list of kvm attributes
* Update and reformat attributes in `kvmrc`
* Update description fom json search - it's just add-on not related to this issue
<hr>
=> B 6548: Update list of kvm attributes

source/intro_release_notes/release_notes/acknowledgements.rst
Modified case of project names in ACKs. These changes are already merged into master.
Realized this should be online now, before the next release, for consistency with other materials, so re-issuing.
Applies to one-6.10 and one-6.10-maintenance
<hr>
=> Modify acks for 6.10

source/management_and_operations/network_management/overview.rst
Fixed broken reference to the self_provision page.
Would apply to master and 6.10
<hr>
=> M #-: Fix broken reference to docs page

source/open_cluster_deployment/storage_setup/nas_ds.rst
Added mention of thin provisioning near the top of the page, also made a few minor alterations for style.
This would apply to master and one-6.10
<hr>
=> M #-: Add mention of thin provisioning in NFS/NAS Datastore page

source/open_cluster_deployment/kvm_node/kvm_driver.rst
=> M #: Polish GA section

source/installation_and_configuration/frontend_installation/opennebula_repository_configuration.rst, source/installation_and_configuration/ha/vm_ha.rst
rhel repo CE code blocks don't work when copying from the doc
```
[root@localhost ~]#  # cat << "EOT" > /etc/yum.repos.d/opennebula.repo
[root@localhost ~]#  [opennebula]
-bash: [opennebula]: command not found
[root@localhost ~]#  name=OpenNebula Community Edition
-bash: Community: command not found
[root@localhost ~]#  baseurl=https://downloads.opennebula.io/repo/7.0/AlmaLinux/$releasever/$basearch
[root@localhost ~]#  enabled=1
[root@localhost ~]#  gpgkey=https://downloads.opennebula.io/repo/repo2.key
[root@localhost ~]#  gpgcheck=1
[root@localhost ~]#  repo_gpgcheck=1
[root@localhost ~]#  EOT
-bash: EOT: command not found
[root@localhost ~]#  # yum makecache
```
EE works
```
[root@localhost ~]# cat << "EOT" > /etc/yum.repos.d/opennebula.repo
> [opennebula]
> name=OpenNebula Enterprise …
```
=> M #: Fix CE rhel repo setup code blocks

source/intro_release_notes/release_notes_enterprise/resolved_issues_6103.rst
=> B OpenNebula/one#2226: Update resolved issues (cluster id)

source/intro_release_notes/release_notes/whats_new.rst, source/management_and_operations/capacity_planning/quotas.rst
=> F OpenNebula/one#6342: Cluster quotas description

source/open_cluster_deployment/storage_setup/ceph_ds.rst
=> M #-: Polish ceph modes table

source/open_cluster_deployment/storage_setup/nas_ds.rst
=> F #6752: Docs for AutoNFS

source/intro_release_notes/release_notes/known_issues.rst
Add https://github.com/OpenNebula/one/issues/6463 (libvirtd restart each 10 minutes) to known issues since one-6.8, which probably made it appear after virsh started being called as oneadmin instead of root from the monitor.
<hr>
=> M #-: Add #6463 to known issues (libvirtd restart each 10 minutes)

source/management_and_operations/references/template.rst
=> M #-: Add ENABLE_SSH context var (windows)

source/integration_and_development/infrastructure_drivers_development/sd.rst
The `increment_flatten` operation was not documented in the first place, so let's use feature https://github.com/OpenNebula/one/issues/6547 as an excuse to do it.
<hr>
=> F OpenNebula/one#6547: Document increment_flatten

source/intro_release_notes/upgrades/upgrading_single.rst
=> M #: LXD is no longer supported

source/intro_release_notes/release_notes_enterprise/resolved_issues_6104.rst
Add support of using defined timezone by oneacct utility with flag -t/--timezone  <https://github.com/OpenNebula/one/issues/821>__.
Branches to which this PR applies
<hr>
=> F OpenNebula/one#821: Added key -t, --timezone to set specific timezone by oneacct

source/management_and_operations/backups/io_limit.rst
A folder ‘datastore’ is missing in the documentation for customising the temporary backup path
<hr>
=> missing folder datastore in path for Temporary Backup Path

source/installation_and_configuration/opennebula_services/scheduler/scheduler.rst, source/installation_and_configuration/opennebula_services/scheduler/scheduler_manager.rst
Scheduler manager introduction
=> f #1550: add scheduler manager introduction

source/intro_release_notes/release_notes_enterprise/resolved_issues_6104.rst
Add Fix VM migration not executed on vCenter when src host ID is 0 https://github.com/OpenNebula/one/issues/6997/
<hr>
=> B OpenNebula/one#6997: VM migration not executed on vCenter when src host ID is 0

source/integration_and_development/system_interfaces/java.rst
=> M #-: Improve java bindings documentation

source/management_and_operations/capacity_planning/scheduler/rank_scheduler.rst
Remove reference to dedicated daemon in introductory paragraph to the Rank Scheduler .
<hr>
=> M #-: Remove ref to sched daemon in Rank Scheduler page

source/intro_release_notes/release_notes_enterprise/resolved_issues_6104.rst
Add an item to resolved issues, pointing to a README update bug.  
fixes OpenNebula/one#7032 
NOTE the file being changed by this commit, does not exist on the `master` and `one-6.10` branches, so we should only apply it to the `-maintance`.
<hr>
=> B OpenNebula/one#7032: Add to resolved issues

source/management_and_operations/end-user_web_interfaces/fireedge_sunstone.rst
Fix column in table to prevent "Malformed table" build error.
(This is synced to 7.0 docs.)
<hr>
=> Fix in table

source/installation_and_configuration/configuration_management/appendix.rst, source/installation_and_configuration/configuration_management/conflicts.rst, source/installation_and_configuration/opennebula_services/fireedge.rst, source/integration_and_development/references/sunstone_dev.rst, source/management_and_operations/end-user_web_interfaces/fireedge_sunstone.rst, source/management_and_operations/users_groups_management/fireedge_sunstone_views.rst
This PR updates the path of the fireedge views
<hr>
=> M #~: fix paths of FireEdge views

.github/workflows/ki_notifier.yml
Add new GitHub Action Workflow to send a notification when a change in Known Issues or Resolved Issues is detected.
<hr>
=> F #-: Add workflow for KI notification

publish/publish.rb
- [ x ] master
- [ x ] one-6.10
- [ x ] one-6.8
<hr>
=> M #-: Fix cleanup of old builds on publish.rb

source/intro_release_notes/release_notes_enterprise/resolved_issues_6105.rst
Re-arranged the time orders when adding a scheduled action in Creating VMs.
<hr>
=>  OpenNebula/one#7031 re-arrange time orders on vm creation

source/open_cluster_deployment/storage_setup/local_ds.rst
improve local DS requirements docs
<hr>
=> M #-: improve local DS requirements docs
