- source/quick_start/deployment_basics/try_opennebula_on_vmware.rst
- source/quick_start/usage_basics/running_kubernetes_clusters.rst
Fixing vOneCenter specifications
Adding note about public IP requirements for OneGate service when running Service Kubernetes template
> M #-: Updating Quick Start Documentation

- source/intro_release_notes/release_notes/whats_new.rst
Change to URL on the Archeon Nebula
> M #-: Update Archeon link

- source/installation_and_configuration/frontend_installation/database.rst
Add mention to MariaDB (@tinova maybe refs or anchors to this sections have to be updated too somewhere else?)
> M #-: Change to MySQL/MariaDB

- source/intro_release_notes/release_notes_enterprise/resolved_issues_641.rst
> B OpenNebula/one#5826: Fix VM.instantiate_name

- source/intro_release_notes/release_notes/known_issues.rst
> B OpenNebula/one#5826: Fix VM.instantiate_name set to false

- source/installation_and_configuration/opennebula_services/database.rst
- source/provision_clusters/hci_clusters/aws_cluster_ceph.rst
> M #-: add warning in database & fix typos

- source/management_and_operations/references/cli.rst
Applies to 6.4 maintenance as well
> Bump CLI links 6.3 -> 6.4

- source/management_and_operations/references/template.rst
> B OpenNebula/one#4995: Fix HOSTNAME param

- source/installation_and_configuration/ha/vm_ha.rst
> B OpenNebula/one#1275: review VMs HA guide

- source/intro_release_notes/release_notes_enterprise/resolved_issues_641.rst
Closes https://github.com/OpenNebula/one/issues/5843
> M #-: Update resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_641.rst
> B OpenNebula/one#5851: Show descriptive console errors

- source/intro_release_notes/release_notes_enterprise/resolved_issues_641.rst
> B OpenNebula/one#5852: Update resolved issues

- source/intro_release_notes/release_notes/whats_new.rst
- source/management_and_operations/multivm_service_management/appflow_use_cli.rst
> F OpenNebula/one#1176: add docs

- source/integration_and_development/system_interfaces/ruby.rst
> M #-: Add missing include

- source/integration_and_development/references/fireedge_sunstone_dev.rst
> M #~: SSO fireedge

- source/intro_release_notes/release_notes_enterprise/resolved_issues_641.rst
> B OpenNebula/one#5873: Fix VM Template creation with memory cost in GB

- source/integration_and_development/system_interfaces/python.rst
> M #5797: update pyone info

- source/installation_and_configuration/large-scale_deployment/sunstone_for_large_deployments.rst
Applies to master and 6.4 as well
> M #: add missing semicolon

- source/intro_release_notes/release_notes/known_issues.rst
Merge to one-6.4-maintenance and one-6.4
> M #-: Add Windows max memory to known issues

- source/installation_and_configuration/opennebula_services/fireedge.rst
> F OpenNebula/one#5780: Add logs documentation

- source/management_and_operations/vm_management/vm_instances.rst
Changing the documentation about VM instance searching to explain the upcoming change to JSON searching
> F #5861: Updating VM search for JSON

- source/installation_and_configuration/large-scale_deployment/sunstone_for_large_deployments.rst
> M #~: Modify FireEdge public endpoint for Apache

- source/intro_release_notes/release_notes_enterprise/resolved_issues_641.rst
> B #Opennebula/one#5889: fix login with externalToken

- source/open_cluster_deployment/storage_setup/ceph_ds.rst
- source/open_cluster_deployment/storage_setup/lvm_drivers.rst
Also related with:
- https://github.com/OpenNebula/one/issues/5838
- https://github.com/OpenNebula/one/issues/3245
> F OpenNebula/one#5886: Add docks for system DS DISK_TYPE

- source/intro_release_notes/release_notes_enterprise/resolved_issues_641.rst
-> master
-> one-6.4-maintenance
Signed-off-by: Carlos J. Herrera <carloshm91@gmail.com>
> F #5834: fix error of zombie VMs

- source/installation_and_configuration/ha/vm_ha.rst
> F OpenNebula/one#3040: add fence_host docs

- source/intro_release_notes/release_notes_enterprise/resolved_issues_641.rst
> B OpenNebula/one#5891: Fix lock/unlock action on Sunstone

- source/intro_release_notes/release_notes_enterprise/resolved_issues_641.rst
> F #5877: add actions on storage app tab

- source/intro_release_notes/release_notes_enterprise/resolved_issues_641.rst
> B OpenNebula/one#5780: Small fixes on the OneProvision GUI

- source/management_and_operations/users_groups_management/showback.rst
> M #-: add note about opennebula-showback.timer

- source/integration_and_development/infrastructure_drivers_development/devel-nm.rst
> M #-: fix typo in networking driver

- source/management_and_operations/capacity_planning/quotas.rst
Merge to one-6.4 and master.
Not sure if we should also mention CLONE_TARGET, LN_TARGET in the quotas section. Maybe referencing this https://docs.opennebula.io/6.4/installation_and_configuration/opennebula_services/oned.html?highlight=clone_target#transfer-driver
> M #-: More info about quotas disk size

- source/intro_release_notes/release_notes_enterprise/resolved_issues_642.rst
> B OpenNebula/one#5912: Update resolved issues

- source/installation_and_configuration/configuration_management/appendix.rst
> M #-: Add guacd file to config docs

- source/intro_release_notes/release_notes/whats_new.rst
Merge only to master
Adds `CONTEXT_RESTRICTED_DIRS` to what's new
> M #-: context restricted dirs to what's new

- source/open_cluster_deployment/storage_setup/onestor_ds.rst
> M #-: Add note about REPLICA_STORAGE_IP

- source/intro_release_notes/release_notes/known_issues.rst
> B #5922 Update known issues

- source/open_cluster_deployment/storage_setup/onestor_ds.rst
* master
* one-6.4
* one-6.2
* one-6.0
> M #-: Add recovery-snapshot passowrd-less req.

- source/installation_and_configuration/whmcs_tenants/configure.rst
> M #-: Fixing path to whmcs module

- source/intro_release_notes/release_notes_enterprise/resolved_issues_642.rst
Adding in improvements/fixed to the 6.4.2 EE Release Notes
> F #5865: updating fixed issues with WHMCS improvements

- source/integration_and_development/system_interfaces/api.rst
Merge to one-6.4 and master
Not sure if use the * or make a new column with async label
> F OpenNebula/one#5943: Notes about async commands

- source/installation_and_configuration/ha/frontend_ha.rst
Applies as well to
- master
- one-6.4 non maintenance
> M #: HA clarification

- source/installation_and_configuration/large-scale_deployment/sunstone_for_large_deployments.rst
> M #~: fix nginx proxy spice

- source/intro_release_notes/release_notes/platform_notes.rst
> M #~: Phusion Passenger is not supported on AlmaLinux 9

- source/intro_release_notes/release_notes_enterprise/resolved_issues_642.rst
Adding resolved issues for https://github.com/OpenNebula/one/issues/5328
> B #5328: Update resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_51213.rst
Inserted information about logrotate changes to 5.12.14 resolved issues
> B OpenNebula/one#5328: Update resolved issues for 5.12.13

- source/intro_release_notes/release_notes_enterprise/resolved_issues_642.rst
> B OpenNebula/one#5981: Fix VMRC issue

- source/installation_and_configuration/opennebula_services/fireedge.rst
> M #~ update config files new sunstone

- source/intro_release_notes/release_notes_enterprise/resolved_issues_643.rst
> F OpenNebula/one#5998: display long labels text

- source/intro_release_notes/release_notes_enterprise/resolved_issues_643.rst
> F #OpenNebula/one#5983: min/max overwrite on update

- source/intro_release_notes/release_notes/known_issues.rst
> M #~: Add Known issue alma9 for VMs with SPICE

- source/intro_release_notes/release_notes_enterprise/resolved_issues_643.rst
> B OpenNebula/one#5993: Fix group creation on Alma9

- source/intro_release_notes/release_notes_enterprise/resolved_issues_643.rst
> B OpenNebula/one#6021: Advanced filters uses regex and substrings

- source/intro_release_notes/release_notes/whats_new.rst
- source/open_cluster_deployment/kvm_node/kvm_driver.rst
> F OpenNebula/one#5753: Two options for live mem resize

- source/intro_release_notes/release_notes_enterprise/resolved_issues_643.rst
> B OpenNebula/one#6026: Fix sunstone oneflow connection

- source/intro_release_notes/release_notes_enterprise/resolved_issues_643.rst
> B OpenNebula/one#5995: Fix show new tickets on support tab

- source/intro_release_notes/release_notes/whats_new.rst
> M #-: Update whats_new.rst

- source/intro_release_notes/release_notes_enterprise/resolved_issues_643.rst
> M #~: Fix resolved issues links

- source/intro_release_notes/release_notes_enterprise/resolved_issues_643.rst
> B OpenNebula/one#5999: Fix filters by labels on FSunstone

- source/intro_release_notes/release_notes_enterprise/resolved_issues_643.rst
> B OpenNebula/one#5839: Fix vnet creation in sunstone 

- source/integration_and_development/automation_tools_integration/ansible.rst
Signed-off-by: Pedro Alvarez Piedehierro <palvarez89@gmail.com>
> Link to Ansible's "one_template" module

- source/provision_clusters/providers/aws_provider.rst
- source/provision_clusters/providers/do_provider.rst
- source/provision_clusters/providers/equinix_provider.rst
- source/provision_clusters/providers/google_provider.rst
- source/provision_clusters/providers/vultr_provider.rst
> B OpenNebula/One#5939: add PLAIN/provision_type

- source/intro_release_notes/release_notes/whats_new.rst
Line 39: not sure about apostrophe in 'context CD's'. Don't use it if it's just a normal plural.  Line 58: Is something missing after 'operation based'? Should it be 'improved operation-based restore'?  Line 86: error from driver --> driver error?
General changes: capitalised Front-end and Back-end, as I think it's usually capitalised in other ON documentation. Also, Virtual Machines.
> M #-: Proofread What's New 6.6

- source/intro_release_notes/release_notes/known_issues.rst
Adding discovered issue for WHMCS Tenants Module for 6.6.x
> M #-: add known WHMCS issue to 6.6

- source/intro_release_notes/release_notes_enterprise/known_issues_ee.rst
Adding discovered issue for WHMCS Tenants Module for 6.4.x
> M #-: add known WHMCS issue

- source/installation_and_configuration/opennebula_services/fireedge.rst
This PR applies:
- one-6.4.maintenance
- master
> M #~: add default zone for fireedge

- source/intro_release_notes/release_notes_enterprise/resolved_issues_661.rst
> B OpenNebula/one#6067: Fix disk RECOVERY_SNAPSHOT_FREQ

- source/intro_release_notes/release_notes_enterprise/resolved_issues_661.rst
> F OpenNebula/one#5974: Schedule Actions improvements

- source/integration_and_development/infrastructure_drivers_development/devel-vmm.rst
Add notes for current KVM driver
> M #-: Update devel-vmm.rst (notes for KVM)

- source/intro_release_notes/release_notes_enterprise/resolved_issues_661.rst
> B OpenNebula/one#6061: Fix issue removing AR on vnet template

- source/intro_release_notes/release_notes/known_issues.rst
- source/intro_release_notes/release_notes_enterprise/resolved_issues_661.rst
Merge to one-6.6-maintenance.
Is it correct, that we have same resolved issues in both 6.4.3 and 6.6.1?
> M #-: Resolved issues: lock, NUMA monitoring, persistent flag

- source/management_and_operations/references/install_steps.txt
> M #-: Update addon-context-windows links

- source/management_and_operations/references/template.rst
> M #: Showcase powershell INIT_SCRIPT

- source/installation_and_configuration/opennebula_services/fireedge.rst
> M #~: Update links to download configuration files

- source/intro_release_notes/release_notes_enterprise/resolved_issues_661.rst
Merge to one-6.6-maintanance.
After 6.4.3 release update release notes for 6.4.4
> B OpenNebula/one#6068: Update release notes

- source/intro_release_notes/release_notes_enterprise/resolved_issues_661.rst
Merge to one-6.6-maintanance.
After 6.4.3 release add to 6.4.4 resolved issues
> B OpenNebula/one#5913: Update release notes

- source/management_and_operations/multivm_service_management/appflow_use_cli.rst
Docs for OneFlow custom role attributes.
> F OpenNebula/one#5591: Oneflow custom role attributes doc

- source/management_and_operations/references/install_steps.txt
> M #: Fix correct Windows Context version

- source/integration_and_development/references/build_deps.rst
- source/integration_and_development/references/compile.rst
* Add some info about scons build parallelization (-j option)
* Update Ubuntu 22.04 dependencies
> M #-: Add some compilation notes

- source/intro_release_notes/release_notes_enterprise/resolved_issues_644.rst
Merge only to one-6.4-maintenance
> B OpenNebula/one#6113: Update release notes

- source/intro_release_notes/release_notes_enterprise/resolved_issues_661.rst
Adding changes from these two issues to the resolved issues list for 6.6.1
> F OpenNebula/one#6044 + OpenNebula/one#6048 - Add resolved

- source/intro_release_notes/release_notes_enterprise/resolved_issues_661.rst
> B OpenNebula/one#6110: add user and password

- source/integration_and_development/infrastructure_drivers_development/overview.rst
Fix name of the "Authentication" driver
> M #-: Fix name of the "Authentication" driver

- source/intro_release_notes/release_notes_enterprise/resolved_issues_661.rst
> B OpenNebula/one#6135: removed duplicated records

- source/intro_release_notes/release_notes_enterprise/resolved_issues_661.rst
> B OpenNebula/one#6088: Eeset backup dialog sunstone

- source/intro_release_notes/release_notes_enterprise/resolved_issues_661.rst
> B OpenNebula/one#6144: Fix scheduled action leases bug

- source/installation_and_configuration/opennebula_services/fireedge.rst
> B OpenNebula/one#6145: default zone endpoint

- source/installation_and_configuration/opennebula_services/fireedge.rst
> B OpenNebula/one#6142: default zone endpoint

- source/intro_release_notes/release_notes_enterprise/resolved_issues_661.rst
> B OpenNebula/one#6125: update name disk

- source/installation_and_configuration/opennebula_services/support.rst
Updated OneGather documentation with the newly implemented functions.
> M #-: Update OneGather documentation

- source/intro_release_notes/release_notes_enterprise/resolved_issues_644.rst
Merge to one-6.4-maintenance, after 6.6.1 release create similar commit for 6.6.2 release notes
> B OpenNebula/docs#6149: Update release notes

- source/intro_release_notes/release_notes_enterprise/resolved_issues_644.rst
> B OpenNebula/one#6114: Update resolved issues

- source/installation_and_configuration/opennebula_services/fireedge.rst
> F OpenNebula/one#6112: remote auth config

- source/intro_release_notes/release_notes/whats_new.rst
- source/management_and_operations/end-user_web_interfaces/fireedge_sunstone.rst
> F OpenNebula/one#6095: Add datastore tab

- source/management_and_operations/references/template.rst
> M #: Add missing OneGate reference

- source/management_and_operations/references/cli.rst
> M #: Fix onegate man link

- source/management_and_operations/references/cli.rst
> M #: Fix CLI man version links

- source/management_and_operations/references/template.rst
> M #: Minor doc fix

- source/intro_release_notes/release_notes/platform_notes.rst
Added details in case that some hosts in a cluster have incompatibility about the version of cgroups mounted
> B #-: Add details about cgroups in host OS updates

- source/installation_and_configuration/ha/vm_ha.rst
- source/intro_release_notes/release_notes_enterprise/resolved_issues_662.rst
Clarify new feature in host_error.rb script
Add github issue OpenNebula/one#6099 to Resolved Issues for 6.6.2
docs were compiled and viewed before commit
> F OpenNebula/one#6099: host_error.rb hook

- source/intro_release_notes/release_notes_enterprise/resolved_issues_644.rst
> B OpenNebula/one#6156: Update resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_662.rst
> F OpenNebula/one#6112: Remote Authorization Support

- source/marketplace/appliances/vnf.rst
Applies to master as well
Closes OpenNebula/addon-context-linux#289
Merge when release
> F OpenNebula/addon-context-linux#275: Document feature

- source/intro_release_notes/release_notes/platform_notes.rst
Merge with https://github.com/OpenNebula/addon-context-linux/pull/290
Merge when release
> OpenNebula/addon-context-linux#288: Update tested platforms

- source/intro_release_notes/release_notes_enterprise/resolved_issues_662.rst
> F OpenNebula/one#6091: reordering the schedule actions

- source/intro_release_notes/release_notes_enterprise/resolved_issues_662.rst
> B OpenNebula/one#6195: Update resolved issues

- source/installation_and_configuration/large-scale_deployment/sunstone_for_large_deployments.rst
> M #~: remove /websockify route nginx

- source/installation_and_configuration/opennebula_services/fireedge.rst
> M #~: changed downloader url for fireedge views

- source/intro_release_notes/release_notes_enterprise/resolved_issues_662.rst
- source/marketplace/appliances/oneke.rst
> F OpenNebula/one#5755: resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_662.rst
> F OpenNebula/one#6201: remove uppercase

- source/marketplace/appliances/oneke.rst
- source/marketplace/appliances/oneke_changelog.rst
- notify users about MetalLB's config changes
- update and move changelog
- minor fixes
> OpenNebula/one#6210: Add note about MetalLB's config changes (OneKE)

- source/intro_release_notes/release_notes/platform_notes.rst
> M #-: Update supported Ceph versions

- source/intro_release_notes/release_notes_enterprise/resolved_issues_643.rst
> M #-: Fix version issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_662.rst
Changing resolved issues link in documentation to link to the doc page relating to the issue (VM High Availability script)
> F OpenNebula/one#6099: Updating docs for correct link

- source/intro_release_notes/release_notes_enterprise/resolved_issues_644.rst
> B OpenneNebula/one#6415: fix size in vmtemplate

- source/intro_release_notes/release_notes_enterprise/resolved_issues_661.rst
> B OpenNebula/one#6415: fix size in vmtemplate

- source/installation_and_configuration/authentication/fireedge.rst
- source/intro_release_notes/release_notes_enterprise/resolved_issues_661.rst
- source/intro_release_notes/release_notes_enterprise/resolved_issues_662.rst
> M #~: update resolved issues 6.6.2

- source/intro_release_notes/release_notes_enterprise/resolved_issues_662.rst
Release notes for https://github.com/OpenNebula/one/issues/6175
> B OpenNebula/one#6175: fix ENV parsing for dockerhub downloader

- source/quick_start/usage_basics/running_kubernetes_clusters.rst
Apply to branches:
- master
- one-6.6
- one-6.4
> M #-: Connect to VFN from front-end

- source/management_and_operations/users_groups_management/accounting.rst
> M #-: Update accounting xsd

- source/open_cluster_deployment/firecracker_node/firecracker_driver.rst
> M #: Fix FC limitations format

- source/intro_release_notes/release_notes_enterprise/resolved_issues_663.rst
> B OpenNebula/One#6222: fix currency in fireedge

- source/installation_and_configuration/opennebula_services/database.rst
- source/intro_release_notes/release_notes_enterprise/resolved_issues_663.rst
40495167b459870e94c9c5fe99dfc1422991a899 applies to master as well
Closes OpenNebula/one#6231
> F OpenNebula#one#6231: Document purge-history for a single VM

- source/intro_release_notes/release_notes_enterprise/resolved_issues_663.rst
- [master](https://github.com/OpenNebula/one-ee/tree/master)
- [one-6.6](https://github.com/OpenNebula/one-ee/tree/one-6.6)
- [one-6.4](https://github.com/OpenNebula/one-ee/tree/one-6.4)
> B OpenNebula/one#6214: Updated BUS_TYPES

- source/intro_release_notes/release_notes_enterprise/resolved_issues_663.rst
Closes https://github.com/OpenNebula/one/issues/5906
> F OpenNebula/one#5906: Update resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_663.rst
> F OpenNebula/one#6239: Update release notes

- source/intro_release_notes/release_notes_enterprise/resolved_issues_645.rst
> F OpenNebula/one#6239: Update resolved issues

- source/management_and_operations/references/cli.rst
Applies to master and one-6.6 as well
> F OpenNebula/one#6006: Add cli listing customizability to doc

- source/intro_release_notes/release_notes/whats_new.rst
> B OpenNebula/one#6246: Update resolved issues

- source/installation_and_configuration/opennebula_services/oned.rst
- source/intro_release_notes/release_notes/whats_new.rst
Merge to master.
Cherry-pick 'Update VM Operation Permissions' commit to one-6.6-maintenance and one-6.4-maintenance
> F 6239: VM Operation Permissions

- source/intro_release_notes/release_notes/whats_new.rst
> F OpenNebula/one#6111: Update what's new

- source/intro_release_notes/release_notes_enterprise/resolved_issues_663.rst
> F OpenNebula/one#6111: Update release notes

- source/intro_release_notes/release_notes_enterprise/resolved_issues_663.rst
> F OpenNebula/one#6239: Update relase notes

- source/installation_and_configuration/frontend_installation/opennebula_repository_configuration.rst
missed the `--dearmor` part in pr #2629
> M #-: Fixed gpg command

- source/intro_release_notes/release_notes_enterprise/resolved_issues_663.rst
> B OpenNebula/one#6193: Update release notes (backup reset flag)

- source/installation_and_configuration/opennebula_services/replace_failing_fe.rst
- source/intro_release_notes/release_notes_enterprise/resolved_issues_663.rst
> F OpenNebula/one#3529: Add resolved issues

- source/_templates/thelayout.html
applies to all branches
master
one-6.4
one-6.2
one-6.0
one-5.12
one-5.10
one-5.8
one-5.6
one-5.4
one-5.2
one-5.0
one-4.14
> M #-: Update GA snippet

- source/intro_release_notes/release_notes/compatibility.rst
- source/intro_release_notes/release_notes/whats_new.rst
- source/marketplace/appliances/vnf.rst
> F OpenNebula/one#6242: Document feature

- source/intro_release_notes/release_notes_enterprise/resolved_issues_663.rst
> B OpenNebula/one#6129: Add disk on template

- source/management_and_operations/backups/backup_jobs.rst
Merge to master.
Remove one duplicated paragraph - there are very similar, I'm not sure if I deleted the correct one.
Change ``onebackupjob sched-add`` to ``onebackupjob backup --schedule``
> F OpenNebula/one#6063: Fix Backup Job description

- source/integration_and_development/system_interfaces/api.rst
- source/management_and_operations/backups/backup_jobs.rst
Merge to master
OpenNebula/one#6063
> F OpenNebula/one#6063: Backup Job xml-rpc API description

- source/intro_release_notes/release_notes/whats_new.rst
https://github.com/OpenNebula/one/issues/5793
> F OpenNebula/one#5793: add VM pmsuspend fix to whats_new

- source/intro_release_notes/release_notes/whats_new.rst
https://github.com/OpenNebula/one/issues/6212
> F OpenNebula/one#6212: add fix for block device in libvirt 7.0+ to whats_new

- source/intro_release_notes/release_notes/whats_new.rst
https://github.com/OpenNebula/one/issues/6167
> F OpenNebula/one#6167: adding io_uring changes to whats_new

- source/intro_release_notes/release_notes_enterprise/resolved_issues_645.rst
> B OpenNebula/one#6297: Update release notes

- source/management_and_operations/vm_management/vm_instances.rst
OpenNebula/one#6063
Merge to master
> F OpenNebula/one#6063: Replace delete-chart and update-chart

- source/intro_release_notes/release_notes_enterprise/resolved_issues_664.rst
Applies to:
- `one-6.6-maintenance`
> B OpenNebula/one#6306: Add to resolved issues

- source/intro_release_notes/release_notes/whats_new.rst
- source/open_cluster_deployment/kvm_node/kvm_driver.rst
Add `Q35_ROOT_PORTS` for q35 PCI port number
> Add `Q35_ROOT_PORTS` for q35 PCI port number

- source/intro_release_notes/release_notes_enterprise/resolved_issues_663.rst
- source/management_and_operations/network_management/manage_vnets.rst
> F OpenNebula/one#6183: Update resolved issues 6.6

- source/intro_release_notes/release_notes_enterprise/resolved_issues_644.rst
- source/management_and_operations/network_management/manage_vnets.rst
> F OpenNebula/one#6183: Update resolved issues 6.4

- source/quick_start/deployment_basics/try_opennebula_on_kvm.rst
> M #-: Recommed t2.medium for MiniONE to avoid OOM

- source/intro_release_notes/release_notes/whats_new.rst
> B OpenNebula/one#6190: Update resolved issues

- source/intro_release_notes/release_notes/whats_new.rst
> F OpenNebula/One#6276: fix deploy VM

- source/intro_release_notes/release_notes_enterprise/resolved_issues_645.rst
> B OpenNebula/One#6062: fix select week days

- source/intro_release_notes/release_notes/whats_new.rst
> B OpenNebula/One#6260: fix select weeks days

- source/intro_release_notes/release_notes/whats_new.rst
> B OpenNebula/one#6154: Fix error on update template

- source/installation_and_configuration/opennebula_services/oned.rst
- source/intro_release_notes/release_notes/whats_new.rst
- source/management_and_operations/vm_management/vm_templates.rst
> B OpenNebula/one#6154: Doc about restricted attributes

- source/intro_release_notes/release_notes/whats_new.rst
> B OpenNebula/one#6331: Update what's new

- source/intro_release_notes/release_notes/whats_new.rst
> F OpenNebula/One#6337: fix decimals inputs resize VM capacity

- source/intro_release_notes/release_notes_enterprise/resolved_issues_645.rst
> B OpenNebula/one#6345: Update resolved issues

- source/integration_and_development/system_interfaces/appflow_api.rst
- source/management_and_operations/multivm_service_management/appflow_use_cli.rst
> M #: Expand oneflow vm_template_contents usage

- source/management_and_operations/vm_management/vm_instances.rst
Applies to everything
We should have it until OpenNebula/addon-context-linux#273 is implemented
> M #: Add VCPU limitation

- source/intro_release_notes/release_notes/whats_new.rst
- source/management_and_operations/end-user_web_interfaces/fireedge_sunstone.rst
Adds the VM group tab docs
---
* **master**
> Add VM Group docs

- source/intro_release_notes/release_notes_enterprise/resolved_issues_681.rst
Adds the vm groups tab to the set of resolved issues
---
* **one-6.8-maintenance**
> F OpenNebula/one#5901: Add vmgroup tab to resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_681.rst
Update resolved issues
---
* **one-6.8-maintenance**
* OpenNebula/one#6347
> B OpenNebula/one#6347: Update resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_681.rst
(cherry picked from commit 9f7fbf8)
> Update resolved issues

- source/intro_release_notes/release_notes/compatibility.rst
Update compatibility guide about label migrator.
---
* **one-6.8**
> M #-: Update compat notes

- source/intro_release_notes/release_notes_enterprise/resolved_issues_681.rst
Update resolved issues with OpenNebula/one#6349
---
* **one-6.8**
> B OpenNebula/one#6349: Update resolved issues

- README.md
- source/quick_start/usage_basics/running_kubernetes_clusters.rst
Some improvements on "Running k8s cluster in AWS" QS guide
> Running k8s clusters improvements

- source/installation_and_configuration/ha/vm_ha.rst
> M #: Fix VM HA script inaccuracy

- source/intro_release_notes/release_notes_enterprise/resolved_issues_681.rst
Update resolved issues to include the fix for OpenNebula/one#6375
---
* **one-6.8**
> B OpenNebula/one#6375: Update resolved issues

- source/intro_release_notes/release_notes/whats_new.rst
> F OpenNebula/One#6323: backupjobs fireedge

- source/integration_and_development/system_interfaces/appflow_api.rst
> M #: Update oneflow recover --delete on REST API

- source/intro_release_notes/release_notes_enterprise/resolved_issues_681.rst
Applies for one-6.8.1 and master
>  B OpenNebula/one#6343: Update resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_681.rst
> F #6393: Change text support tab

- source/intro_release_notes/release_notes_enterprise/resolved_issues_681.rst
> B OpenNebula/one#6354: Update resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_681.rst
> B OpenNebula/one#6221: size in MB and GB

- source/intro_release_notes/release_notes_enterprise/resolved_issues_681.rst
> B OpenNebula/One#6385: OTP time

- source/intro_release_notes/release_notes_enterprise/resolved_issues_681.rst
> B OpenNebula/One#6334: kernel and ramdisk

- source/management_and_operations/end-user_web_interfaces/fireedge_sunstone.rst
Add modifications on doc about groups that I forgot in the previous PR.
> F OpenNebula#6122: Modify FireEdge doc with groups

- source/intro_release_notes/release_notes_enterprise/resolved_issues_681.rst
Modify doc to explain how to download new group tab views on 6.8
> F OpenNebula#6122: Resolved issue group tabs

- source/intro_release_notes/release_notes/whats_new.rst
Update what's new about restricted attributes.
> F OpenNebula/one#6332: Update what's new

- source/intro_release_notes/release_notes_enterprise/resolved_issues_681.rst
Update resolved issues with restricted attributes.
> F OpenNebula/one#6332: Update resolved issues 681

- source/intro_release_notes/release_notes_enterprise/resolved_issues_681.rst
> F OpenNebula/one#6059: Update resolved issues

- source/installation_and_configuration/opennebula_services/scheduler.rst
COLD_MIGRATE_MODE clarification is added
Applies for master, 6.8 and 6.4.
> M #-: COLD_MIGRATE_MODE clarification

- source/intro_release_notes/release_notes_enterprise/resolved_issues_681.rst
Adding fix to resolved issues for: https://github.com/OpenNebula/one/issues/6391
> B OpenNebula/one-ee#6391 - Resolved Issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_681.rst
> B OpenNebula/One#6340: fix request create marketplace app

- source/intro_release_notes/release_notes/whats_new.rst
> B OpenNebula/one#6425: Update whats new

- source/intro_release_notes/release_notes_enterprise/resolved_issues_681.rst
> F OpenNebula/one#6356: Add oneflow CLI formatting

- source/installation_and_configuration/opennebula_services/fireedge.rst
Updated the download link to the new config files.
Link:
```
https://bit.ly/one-681-config 
=>
https://minhaskamal.github.io/DownGit/#/home?url=https:%2F%2Fgithub.com%2FOpenNebula%2Fone%2Ftree%2F725337ea5eaf4ca2dd7539db5e300edfc94ddde5%2Fsrc%2Ffireedge%2Fetc 
=>
https://github.com/OpenNebula/one/tree/725337ea5eaf4ca2dd7539db5e300edfc94ddde5/src/fireedge/etc
```
<hr>
> M OpenNebula/one#5687: Updated config download link

- source/intro_release_notes/release_notes_enterprise/resolved_issues_646.rst
Fix request create a marketplace app when the marketplace 0 is disabled
> B OpenNebula/One#6340: create marketapp

- source/intro_release_notes/release_notes/known_issues.rst
> M #-: Add RAW/DATA to known issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_682.rst
Add `Fix Monitoring encryption` to resolved issues
<hr>
> B OpenNebula/one#6445: Update resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_682.rst
Update resolved issues - Fix possible segfault in VM disk resize
<hr>
> B OpenNebula/one#6432: Update resolved issues

- source/management_and_operations/vm_management/vm_instances.rst
Description and examples modified:
* CLI output
* Scheduled action update
* Remove obsolete 'warning' attribute
* Add link to Scheduled Action Template
Merge to 6.8 and master
> M #-: Update Scheduled Action description to match actual code

- source/intro_release_notes/release_notes/whats_new.rst
> B OpenNebula/one#6380: Add fix issue 6380

- source/intro_release_notes/release_notes_enterprise/resolved_issues_682.rst
> B OpenNebula/one#6418

- source/open_cluster_deployment/storage_setup/ceph_ds.rst
> M #-: Remove typo

- source/quick_start/deployment_basics/try_opennebula_on_kvm.rst
- source/quick_start/usage_basics/running_kubernetes_clusters.rst
> M #-: Add note about public IP for OneGate to QS

- source/installation_and_configuration/ha/frontend_ha.rst
- source/installation_and_configuration/large-scale_deployment/sunstone_for_large_deployments.rst
- source/integration_and_development/automation_tools_integration/docker_machine.rst
- source/integration_and_development/references/fireedge_sunstone_dev.rst
- source/locale/es/LC_MESSAGES/administration/sunstone_gui/suns_views.po
- source/locale/es/LC_MESSAGES/administration/virtualization/evmwareg.po
- source/locale/es/LC_MESSAGES/advanced_administration/cloud_bursting/ec2g.po
- source/locale/es/LC_MESSAGES/integration/cloud_interfaces/occidd.po
- source/marketplace/appliances/overview.rst
- source/open_cluster_deployment/storage_setup/lvm_drivers.rst
> M #-: Remove "the the" typo

- source/intro_release_notes/release_notes_enterprise/resolved_issues_682.rst
Add virtual network template tab in fireedge
> F OpenNebula/one#6118: add vnet template tab

- source/intro_release_notes/release_notes/whats_new.rst
- source/management_and_operations/capacity_planning/external.rst
> F OpenNebula/one#6474: Add host_id to External Scheduler

- source/intro_release_notes/release_notes_enterprise/resolved_issues_682.rst
Add [#6448](https://github.com/OpenNebula/one/issues/6448) to resolved issues.
<hr>
> B OpenNebula/one#6448: Update resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_646.rst
Add to release notes: Fix monitoring in HA
<hr>
> B OpenNebula/one#6372: Update release notes

- source/intro_release_notes/release_notes_enterprise/resolved_issues_646.rst
Add fix quotas to release notes
<hr>
> B OpenNebula/one#6355: Update resolved issues

- source/integration_and_development/references/build_deps.rst
* Merge Ubuntu 20.04 and 22.04 dependencies
* Remove bison and flex - generating parsers in build doesn't work
* Remove non-existing libs
* Add bower, grunt and scons dependency
* Add one-liner to install all dependencies
<hr>
> M #-: Update build dependencies for Ubuntu and Debian

- source/intro_release_notes/release_notes/whats_new.rst
- source/management_and_operations/end-user_web_interfaces/fireedge_sunstone.rst
Add OneFlow docs to `Management and Operations` and `What's New`
<hr>
> F OpenNebula/one#5833: Add oneflow docs

- source/intro_release_notes/release_notes_enterprise/resolved_issues_646.rst
Add to the resolved issues the fix to OpenNebula/one#5768
<hr>
> B OpenNebula/one#5768: Fix oneflow client adding uri prefix path to the http request path

- source/intro_release_notes/release_notes_enterprise/resolved_issues_682.rst
Supported custom attributes at Python binding.
<hr>
> F #4188: Supported custom attributes at Python binding

- source/intro_release_notes/release_notes/whats_new.rst
Add OpenNebula/one#6490 to what's new section
<hr>
> F OpenNebula/one#6490: Added to what's new

- source/intro_release_notes/release_notes_enterprise/resolved_issues_682.rst
* Update resolved issues
* Added "fix"- prefix to all resolved issues
* Moved VN Templates tab to backported section
<hr>
> B OpenNebula/one#6384: Update resolved issues

- source/intro_release_notes/release_notes/whats_new.rst
Add OpenNebula/one#6384 to what's new section
<hr>
> B OpenNebula/one#6384: Added to what's new

- source/intro_release_notes/release_notes_enterprise/resolved_issues_682.rst
Add OpenNebula/one#6507 to resolved issues
<hr>
> B OpenNebula/one#6507: Update resolved issues

- source/intro_release_notes/release_notes/whats_new.rst
Add OpenNebula/one#6507 to what's new section
<hr>
> B OpenNebula/one#6507: Added to what's new

- source/intro_release_notes/release_notes_enterprise/index.rst
- source/intro_release_notes/release_notes_enterprise/resolved_issues_683.rst
> B OpenNebula/one#6506: Update resolved issues 6.8.3

- source/intro_release_notes/release_notes_enterprise/resolved_issues_683.rst
This PR adds support tab to fireedge
> B OpenNebula/One#5909: support tab

- source/intro_release_notes/release_notes_enterprise/resolved_issues_683.rst
Reported the addition of QS link to README.md
<hr>
> F#6513: Add QS to README.md

- source/intro_release_notes/release_notes_enterprise/resolved_issues_646.rst
Add https://github.com/OpenNebula/one/issues/6472 to resolved issues
<hr>
> B OpenNebula/one#6472: Update resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_683.rst
Update resolved issues
+ cherrypick the description from master branch
<hr>
> F OpenNebula/one#6269: Update resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_683.rst
this PR fixes the zone tab in fireedge
<hr>
> F OpenNebula/One#6120: zone tab

- source/intro_release_notes/release_notes_enterprise/resolved_issues_683.rst
> F OpenNebula/one#6117: Marketplace on release notes in 6.8

- source/intro_release_notes/release_notes_enterprise/resolved_issues_683.rst
Fix disk size after snapshot-revert added to release notes
<hr>
> B OpenNebula/one#6503: Update release notes

- source/intro_release_notes/release_notes/whats_new.rst
> B OpenNebula/one#6528: Update resolved issues

- source/integration_and_development/references/sunstone_dev.rst
- source/marketplace/public_marketplaces/index.rst
- source/marketplace/public_marketplaces/overview.rst
- Marketplace refs
- Warning on Sunstone development process
<hr>
> M #-: Minor issues on documentation

- source/intro_release_notes/release_notes_enterprise/resolved_issues_683.rst
Add fix of Scheduled Actions to release notes
<hr>
> B OpenNebula/one#6541: Update resolved issues

- source/intro_release_notes/release_notes/whats_new.rst
> B OpenNebula/one#5921: Update resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_683.rst
> B OpenNebula/one#6533: Update release notes (no_check_capacity)

- source/intro_release_notes/release_notes/compatibility.rst
> B OpenNebula/one#6533: Compatibility note for no_check_capacity

- source/integration_and_development/system_interfaces/api.rst
Over time the reference to XSD moved away from the caption, bring it back
<hr>
> M #-: Fix xsd reference

- source/intro_release_notes/release_notes_enterprise/resolved_issues_646.rst
> B OpenNebula/one#6481: Modification on onecfg help in order not to show version parameter (6.4)

- source/intro_release_notes/release_notes_enterprise/resolved_issues_683.rst
> B OpenNebula/one#6481: Modification on onecfg help in order not to show version parameter (6.8)

- source/intro_release_notes/release_notes_enterprise/resolved_issues_683.rst
> B OpenNebula/one#6542: Update resolved issues (Scheduled Actions)

- source/intro_release_notes/release_notes_enterprise/resolved_issues_683.rst
> B OpenNebula/one#6530: Update resolved issues (SPICE passwd)

- source/intro_release_notes/release_notes_enterprise/resolved_issues_646.rst
> B OpenNebula/one#6530: Update resolved issues (SPICE password)

- source/overview/opennebula_concepts/opennebula_overview.rst
Fix typo on Edge Cluster section under the OpenNebula Overview
<hr>
> M #-: Fix typo on Edge Cluster section under the OpenNebula Overview

- source/intro_release_notes/release_notes/compatibility.rst
> Update compatibility guide

- source/intro_release_notes/release_notes_enterprise/resolved_issues_683.rst
> B OpenNebula/one#6550: Update resolved issues (backup Scheduled Action)

- source/intro_release_notes/release_notes_enterprise/resolved_issues_683.rst
* Add OpenNebula/one#6529 to resolved issues
<hr>
> F OpenNebula/one#6529: Update resolved issues

- source/intro_release_notes/release_notes/whats_new.rst
* Add OpenNebula/one#6537 to whats new notes
<hr>
> F OpenNebula/one#6537: Update whats new

- source/intro_release_notes/release_notes/whats_new.rst
* Add OpenNebula/one#5899 to whats new notes.
<hr>
> F OpenNebula/one#5899: Update whats new

- source/intro_release_notes/release_notes_enterprise/resolved_issues_683.rst
> B OpenNebula/one#6543: Update resolved issues (MySQL reconnection)

- source/open_cluster_deployment/storage_setup/local_ds.rst
Updated Local Storage Datastore
- Added note on QCOW2_OPTIONS attribute
- Fixed typo
<hr>
> B OpenNebula/one#6487

- source/intro_release_notes/release_notes_enterprise/resolved_issues_683.rst
Adding OpenNebula/one#6545 to resolved issues.
> B OpenNebula/one#6545: Update resolved issues

- source/management_and_operations/storage_management/datastores.rst
> M OpenNebula/one#6561: Describe LIMIT_MB

- source/intro_release_notes/release_notes_enterprise/resolved_issues_683.rst
> F OpenNebula/one#6561: Update resolved issues (LIMIT_MB)

- source/intro_release_notes/release_notes/known_issues.rst
> B OpenNebula/one#6565: Update known issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_684.rst
> B #6476: Release READY attribute for VMs which were terminated

- source/intro_release_notes/release_notes/whats_new.rst
Add issue solved (host table update after creating a new host)
<hr>
> B OpenNebula/one#6451: refresh host table

- source/installation_and_configuration/authentication/fireedge.rst
This PR adds LDAP auth documentation for fireedge
<hr>
> F OpenNebula/One#6514: Add LDAP auth to fireedge

- source/intro_release_notes/release_notes_enterprise/resolved_issues_684.rst
> B OpenNebula/one#6580: Update resolved issues (oned crash)

- source/intro_release_notes/release_notes/whats_new.rst
Only What's new updated
Picture [VM states complete](https://github.com/OpenNebula/docs/blob/master/source/images/states-complete.png) needs update, but it's missing also Backup, Restore states. I'll update it as separate commit
<hr>
> F OpenNebula/one#6498: Update what's new (recover recreate)

- source/intro_release_notes/release_notes/whats_new.rst
Note about virtual machine template issues:
- https://github.com/OpenNebula/one/issues/6518
- https://github.com/OpenNebula/one/issues/6515
- https://github.com/OpenNebula/one/issues/6516
- https://github.com/OpenNebula/one/issues/6485
- https://github.com/OpenNebula/one/issues/6501
- https://github.com/OpenNebula/one/issues/6495
<hr>
> M #-: Note about virtual machine template issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_684.rst
Add note about group views in the resolved issues.
<hr>
> F OpenNebula/one#6399: Add note in resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_684.rst
Adds resolved issue entry for removing disk number/naming limitations
> F OpenNebula/one#6291: disk limitations add to resolved issues

- source/intro_release_notes/release_notes/whats_new.rst
Update what's new to mention enhancement of placement tab in FSunstone
<hr>
> F OpenNebula/one#6419: Update what's new (placement tab)

- source/intro_release_notes/release_notes_enterprise/resolved_issues_684.rst
> B OpenNebula/one#6471: Change user's password issue resolved

- source/intro_release_notes/release_notes_enterprise/resolved_issues_684.rst
* Add OpenNebula/one#6447 to resolved issues
<hr>
> F OpenNebula/one#6447: Update resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_683.rst
* Add OpenNebula/one#6417 to resolved issues
<hr>
> F OpenNebula/one#6417: Update resolved issues

- source/intro_release_notes/release_notes/whats_new.rst
> B OpenNebula/One#6562: fix comments in sunstones view

- source/intro_release_notes/release_notes/whats_new.rst
> B OpenNebula/One#6386: remove unnecesary step creating an image

- source/intro_release_notes/release_notes/whats_new.rst
> F OpenNebula/One#6613: fix detailed view stuck in fullscreen

- source/intro_release_notes/release_notes/whats_new.rst
> F OpenNebula/One#6075: simplified view table instantiate vm

- source/intro_release_notes/release_notes_enterprise/resolved_issues_684.rst
* Add OpenNebula/one#6484 to resolved issues
<hr>
> B OpenNebula/one#6484: Update resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_647.rst
> F OpenNebula/one#6630: Update resolved issues

- source/management_and_operations/monitor_alert/alerts.rst
- source/management_and_operations/monitor_alert/grafana.rst
- source/management_and_operations/monitor_alert/install.rst
Refactor:
* Overview
* Installation and configuration
* Grafana Visualization
* Alert Manager
* Exporter Metrics
<hr>
> F OpenNebula/one#6430: Refactor Monitoring section

- source/intro_release_notes/release_notes/whats_new.rst
https://github.com/OpenNebula/one/issues/6305
<hr>
> B OpenNebula/whats_new#6305: Fixing oneflow delete function

- source/legacy_components/ruby_sunstone/index.rst
- source/legacy_components/ruby_sunstone/ruby_sunstone_views.rst
- source/legacy_components/ruby_sunstone/sunstone.rst
- source/management_and_operations/users_groups_management/index.rst
- source/management_and_operations/vm_management/vm_templates.rst
Move Sunstone views to legacy section and update some references to Sunstone views.
<hr>
> F OpenNebula/one#6430: Move Sunstone views to legacy section

- source/management_and_operations/users_groups_management/showback.rst
There is no vm cost when you instantiate a vm. That is gonna be solved in https://github.com/OpenNebula/one/issues/6639 but for now, we delete the screenshot.
<hr>
> F OpenNebula/one#6430: Delete vm screenshot until 6639 issue is solved

- source/intro_release_notes/upgrades/upgrading_federation.rst
- source/intro_release_notes/upgrades/upgrading_ha.rst
- source/intro_release_notes/upgrades/upgrading_single.rst
Sunstone review of Upgrades section
<hr>
> F OpenNebula/one#6430: Sunstone review of Upgrades section

- source/installation_and_configuration/ha/frontend_ha.rst
- source/installation_and_configuration/large-scale_deployment/fireedge_for_large_deployments.rst
- source/installation_and_configuration/large-scale_deployment/index.rst
- source/installation_and_configuration/large-scale_deployment/overview.rst
- source/installation_and_configuration/large-scale_deployment/scalability.rst
- source/legacy_components/ruby_sunstone/index.rst
- source/legacy_components/ruby_sunstone/sunstone.rst
- source/legacy_components/ruby_sunstone/sunstone_for_large_deployments.rst
- source/legacy_components/vcenter_driver/vcenter_driver.rst
- source/locale/es/LC_MESSAGES/administration/sunstone_gui/sunstone.po
- source/locale/es/LC_MESSAGES/advanced_administration/scalability/one_scalability.po
- source/marketplace/appliances/marketapps.rst
- source/marketplace/private_marketplaces/market_http.rst
- source/marketplace/private_marketplaces/market_s3.rst
this PR fixes the large-scale and HA settings
<hr>
> F OpenNebula/One#6430: large-scale and HA

- source/intro_release_notes/release_notes/whats_new.rst
add issue documentation 6637
<hr>
> B OpenNebula/One#6637: fix vm graphs

- source/management_and_operations/references/creating_images.rst
- source/management_and_operations/references/template.rst
Added note about legacy vcenter driver in templates page, and a couple of minor fixes.
<hr>
> F OpenNebula/one#6642: Adjust documentation for 6.10 active components

- source/management_and_operations/multivm_service_management/appflow_use_cli.rst
No code modified, just an improvement of the `custom_attrs` section since until now it was a little confuse on how to use it.
<hr>
> B OpenNebula/one#6359: Improve OneFlow's custom_attrs documentation

- source/intro_release_notes/release_notes/whats_new.rst
Replaced bullet list with tables for deprecated & legacy components in What's New
<hr>
> M #-: 6.10 RNs add table in What's New

- source/intro_release_notes/release_notes/acknowledgements.rst
Acknoledgements for 6.10.
<hr>
> M #-: 6.10 RN Acknowledgements

- source/intro_release_notes/release_notes/whats_new.rst
>    B OpenNebula/one#6571: Add link to fixed issue (6571)

- source/intro_release_notes/release_notes/acknowledgements.rst
Removed IPCEI-CIS link from 2nd bullet item
<hr>
> M #-: 6.10 RN Acknowledgements remove 1 link

- source/installation_and_configuration/opennebula_services/database.rst
- source/intro_release_notes/release_notes/whats_new.rst
> F OpenNebula/one#6567: fsck dry flag

- source/intro_release_notes/release_notes/whats_new.rst
- source/open_cluster_deployment/kvm_node/kvm_driver.rst
> F OpenNebula/one#6645: Document feature

- source/intro_release_notes/release_notes/whats_new.rst
Add the issue https://github.com/OpenNebula/one/issues/6656 to the what's new section of the release notes.
<hr>
> B OpenNebula/one#6656: Add link to fix issue (6656) (#3168)

- source/intro_release_notes/release_notes/whats_new.rst
Add link to fix issue (6634)
<hr>
> Add link to fix issue (6634)

- source/installation_and_configuration/large-scale_deployment/scalability.rst
> M #-: Update scalability results

- source/installation_and_configuration/large-scale_deployment/scalability.rst
Changed "Ver" to "Version" so this doc passes spelling test.
<hr>
> M #-: Fix word to pass spelling test

- source/intro_release_notes/release_notes/whats_new.rst
- source/management_and_operations/references/template.rst
- source/management_and_operations/vm_management/vm_instances.rst
> M #-: Add Scheduled Action Warning

- source/integration_and_development/references/compile.rst
Update build information:
* Add download flag
* Add default values
* Mark parsers as obsolete, building parsers doesn't work
<hr>
> M #-: Build: Add download flag, add defaults

- source/integration_and_development/references/compile.rst
Fixed a typo ("(3rdParty", line 63) that was causing the spellchecker to complain
Took the chance to capitalize some proper nouns.
<hr>
> M #-: Fix typo in compile.rst

- source/quick_start/operation_basics/operating_edge_cluster.rst
Reviewed the text for style, for the 6.10 launch.
The spellcheck will fail for this PR due to typo in integration_and_development/references/compile.rst, which was fixed in another branch (in [https://github.com/OpenNebula/docs/pull/3007](url)) but is not merged yet.
<hr>
> M #-: Review Operating Edge Cluster for style

- source/quick_start/deployment_basics/overview.rst
- source/quick_start/deployment_basics/try_opennebula_on_kvm.rst
- source/quick_start/index.rst
- source/quick_start/operation_basics/overview.rst
- source/quick_start/usage_basics/overview.rst
Retouch texts in linking pages in the Quick Start section, such as the index.rst and overview.rst.
<hr>
> M #-: 6.10 Retouches to Quick Start Section

- source/installation_and_configuration/configuration_management/appendix.rst
Run the files2rst script to update list of config files as per https://github.com/OpenNebula/infra/wiki/Configuration-Migration
<hr>
> M #-: 6.10 Update list of config files

- source/overview/opennebula_concepts/key_features.rst
- source/quick_start/deployment_basics/try_opennebula_hosted.rst
- source/quick_start/deployment_basics/try_opennebula_on_kvm.rst
- source/quick_start/usage_basics/running_kubernetes_clusters.rst
- source/quick_start/usage_basics/running_virtual_machines.rst
Fix a broken link in Running K8s Clusters
In the Overview & QS Guide reformat some external links for consistency i.e. adhere to `label <https://link.com>`__
<hr>
> M #-: Fix Broken link and make external links consistent

- source/intro_release_notes/release_notes/known_issues.rst
- source/intro_release_notes/release_notes/whats_new.rst
Remove mention of Beta version and of OneProvision repositories
<hr>
> M #-: Release Notes: Remove mentions of Beta and OneProvision

- source/intro_release_notes/upgrades/upgrading_single.rst
> B OpenNebula/one#6591: Warn about problem in upgrade doc section

- source/overview/opennebula_concepts/opennebula_overview.rst
Removed mention of deprecated OneGate/Proxy from Overview.
<hr>
> M #-: Remove mention of OneGate Proxy

- source/intro_release_notes/release_notes/whats_new.rst
Add information about the fix for the GH issue #[6686](https://github.com/OpenNebula/one/issues/6686) into "What's new" section of Release notes.
<hr>
> B OpenNebula/one#6686: Add info about fix to What's new

- source/intro_release_notes/upgrades/upgrading_single.rst
Minor corrections for style
<hr>
> M #-: Minor text review

- source/installation_and_configuration/frontend_installation/install.rst
> M #-: Update provision deps installation

- source/intro_release_notes/release_notes/compatibility.rst
Explain labels compatibility in Sunstone with the new and old Sunstone.
<hr>
> M #-: Explain labels compatibility in Sunstone

- source/index.rst
- source/installation_and_configuration/automatic_deployment/index.rst
- source/installation_and_configuration/automatic_deployment/one_deploy_tutorial_shared_ds.rst
- source/quick_start/deployment_basics/index.rst
- source/quick_start/deployment_basics/try_opennebula_on_vmware.rst
Modify titles, ToC entries for Automatic Deployment Guides
Remove "Broadcom" from vOneCloud guide
Minor corrections in OneDeploy Shared Storage tutorial
<hr>
> M #-: Corrections to Automatic Deployment Guides, ToC

- source/installation_and_configuration/automatic_deployment/index.rst
- source/quick_start/deployment_basics/index.rst
- source/quick_start/deployment_basics/try_opennebula_on_kvm.rst
- source/quick_start/deployment_basics/try_opennebula_onprem.rst
- Added short tutorial for miniONE on-prem without hypervisor node
- Minor modification to ToC to make title appear on single line
<hr>
> M #-: 6.10 minione onprem guide

- source/intro_release_notes/release_notes/whats_new.rst
- Added paragraphs for Automated Installation (OneDeploy) and automatic VM migration from VMware
- Added small subsections for each of them
<hr>
> M #-: Add onedeploy and oneswap to Whats New

- source/intro_release_notes/release_notes/whats_new.rst
Add the issue https://github.com/OpenNebula/one/issues/6508 to the what's new section of the release notes.
<hr>
> B OpenNebula/one#6508: Add link to fix issue (6508) (#3204)

- source/installation_and_configuration/opennebula_services/fireedge.rst
- source/intro_release_notes/release_notes_enterprise/resolved_issues_6101.rst
* Add note + link pointing to new Sunstone/OneProvision configuration download
<hr>
> B OpenNebula/one#6711: Update resolved issues

- source/management_and_operations/multivm_service_management/appflow_elasticity.rst
Provided more precise definition of OneFlow service auto-scaling.
<hr>
> M #-: More precise definition of OneFlow auto-scaling

- source/intro_release_notes/upgrades/overview.rst
- source/intro_release_notes/upgrades/start_here.rst
- source/intro_release_notes/upgrades/upgrading_single.rst
Remove reference to migrator package online form in the 6.8 documentation
<hr>
> M #-: Remove reference to migrator package in 6.8

- source/integration_and_development/references/compile.rst
> F #6577: Adjust pyone deps

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6101.rst
> F #6577: Add to resolved issues

- source/intro_release_notes/release_notes/known_issues.rst
Known issue about vrouters.
<hr>
> M #-: Known issue about vrouters

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6101.rst
> B OpenNebula/one#6725: Add 6725 on resolved issues

- source/intro_release_notes/release_notes/known_issues.rst
* Groupadmin view fails to load for groups with multiple admins
<hr>
> B OpenNebula/one#6730: Update known issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6101.rst
Added the `onevm disk-snapshot-list` cli command.
<hr>
> F OpenNebula/one#6624: Add disk snapshot list

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6101.rst
> B OpenNebula/one#6596: Update resolved issues (CPU pinning)

- source/intro_release_notes/release_notes/whats_new.rst
> F OpenNebula/one#6703: Update what's new

- source/management_and_operations/end-user_web_interfaces/fireedge_sunstone.rst
Remove vmrc attribute in Firedge config table.
<hr>
> B OpenNebula/one#6736: Remove vmrc attribute in Firedge config

- source/intro_release_notes/release_notes/compatibility.rst
Remove vmrc attribute in Firedge config table.
<hr>
> B OpenNebula/one#6736: Add compatibility note about vmrc in Sunstone

- source/intro_release_notes/release_notes/known_issues.rst
* Add RSunstone patches & instructions on how to apply them
<hr>
> B #-: Update known issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6101.rst
> F OpenNebula/One#6718:update resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6101.rst
> F OpenNebula/one#2111: Update resolved issues (VM histories)

- source/integration_and_development/infrastructure_drivers_development/sd.rst
Document interface changes in DS.backup.
<hr>
> F OpenNebula/One#6411: update DS.backup op interface

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6101.rst
* Add OpenNebula/one#6746 to resolved issues
<hr>
> B OpenNebula/one#6746: Update resolved issues

- source/management_and_operations/backups/operations.rst
- source/management_and_operations/backups/overview.rst
> F OpenNebula/one#6411: update incremental backup docs

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6101.rst
> F OpenNebula/one#6411: update resolved_issues

- README.md
- source/integration_and_development/infrastructure_drivers_development/sd.rst
Fix syntax error (&). Also, add missing compile dependency.
<hr>
> Fix 860e3ffa (sphinx syntax error)

- README.md
Fix sphinx required version in README, for local builds
<hr>
> F #-: Pin sphinx versions to avoid build errors

- source/installation_and_configuration/frontend_installation/opennebula_repository_configuration.rst
Remove leading white spaces in RHEL and AlmaLinux command blocks for easier copy and paste.
<hr>
> Fix white spaces

- source/integration_and_development/references/build_deps.rst
> M #-: Update build dependencies

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6101.rst
Closes OpenNebula/one#6758
<hr>
> B OpenNebula/one#6758: Fix QEMU_GA ping monitoring

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6101.rst
> Update resolved_issues (issue 6712)

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6101.rst
> B OpenNebula/one#6726: Update resolved issues (CLI parameters)

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6101.rst
Add some Sunstone issues that were resolved on 6.10.1
<hr>
> M #-: Sunstone resolved issues on 6.10.1

- source/installation_and_configuration/opennebula_services/fireedge.rst
* Update Sunstone config download link to => https://github.com/OpenNebula/one/tree/0bd451171fb6551f8dc8f7d5b38ab6ec9f6a9cef/src/fireedge/etc
<hr>
> M #-: Update config download link

- source/ext/spellchecking/wordlists/opennebula.txt
- source/intro_release_notes/upgrades/upgrading_single.rst
Update doc about upgrade 6.10.1
<hr>
> M #-: Upgrade to 6.10.1 docs

- source/intro_release_notes/release_notes/platform_notes.rst
Remove Pacific (EOL), add Quincy.
<hr>
> F #-: Update Ceph supported releases

- source/ext/spellchecking/wordlists/opennebula.txt
- source/integration_and_development/system_interfaces/api.rst
Add `one.zone.*server` methods description.
Fix few typos (copy paste errors)
<hr>
> M #-: Add missing commands to xml-rpc api

- source/intro_release_notes/release_notes_enterprise/resolved_issues_647.rst
Add https://github.com/OpenNebula/one/issues/6791 to resolved_issues.
<hr>
> B OpenNebula/one#6791: DS ceph export: use CEPH_KEY

- source/management_and_operations/host_cluster_management/hosts.rst
> F OpenNebula/one#6723: Deprecated note for import VM command

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6102.rst
* Add `onedb fsck` to resolved issue.
* Fix references format for all resolved issues
<hr>
> B OpenNebula/one#6793: Update resolved issues (onedb fsck)

- source/ext/spellchecking/wordlists/opennebula.txt
Added 3 words to prevent spellchecking errors.
<hr>
> M #-: Add words to spellchecking dictionary

- source/intro_release_notes/release_notes/acknowledgements.rst
Changed case to ONEedge5G and ONEnextgen, modified phrase in ACKs.
<hr>
> M #-: Change case of project names and 1 phrase in ACKs

- source/intro_release_notes/release_notes/acknowledgements.rst
Changed case of project names and 1 phrase in ACKs.
Already in master, applies to one-6.10 & one-6.10-maintenance
<hr>
> Change case of project names in ACKs

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6102.rst
Adding release note for filter by locked fixed
<hr>
> Opennebula/docs#6768: Adding release note for filter by locked fixed

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6102.rst
* Add OpenNebula/one#6788 to resolved issues
<hr>
> B OpenNebula/one#6788: Update resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6102.rst
* Add OpenNebula/one#6757 to resolved issues
<hr>
> B OpenNebula/one#6757: Update resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_648.rst
Update link to milestone 6.4.8
<hr>
> M #-: Update link to release 6.4.8

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6102.rst
* Add OpenNebula/one#6716 to resolved issues
<hr>
> B OpenNebula/one#6716: Update resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6102.rst
Closes OpenNebula/one#6765
<hr>
> B OpenNebula/one#6765: Update resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6102.rst
Add OpenNebula/one#6817 to resolved issues
<hr>
> B OpenNebula/one#6817: Add 6817 issue to resolved issues

- source/ext/spellchecking/wordlists/opennebula.txt
- source/intro_release_notes/release_notes_enterprise/resolved_issues_6102.rst
- source/open_cluster_deployment/networking_setup/bridged.rst
- source/open_cluster_deployment/networking_setup/vlan.rst
Review and update resolved issues.
<hr>
> M #-: Update resolved issues 6.10.2

- source/installation_and_configuration/opennebula_services/fireedge.rst
* Updates the fireedge config download link, pointing to => `https://github.com/OpenNebula/one/tree/ebc5b95b86b7867f6919a108909a70d2c28032ef/src/fireedge/etc`
<hr>
> M #-: Update fireedge config download link

- source/intro_release_notes/release_notes/known_issues.rst
* Adds workaround instructions to bug introduced in OpenNebula/one#6757
<hr>
> B OpenNebula/one#6757: Add workaround instructions

- source/installation_and_configuration/ha/vm_ha.rst
> M #: Document SSH timeouts on VM HA

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6103.rst
* Add OpenNebula/one#6846 to resolved issues
<hr>
> B OpenNebula/one#6846: Update resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6103.rst
> B OpenNebula/one#6823: Update release notes (quota)

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6103.rst
Add 6820 issue to resolved issues.
<hr>
> B OpenNebula/one#6820: Add 6820 to resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6103.rst
* Add OpenNebula/one#6794 to resolved issues
<hr>
> B OpenNebula/one#6794: Update resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6103.rst
* Adds OpenNebula/one#6816 to resolved issues
<hr>
> B OpenNebula/one#6816: update resolved issues

- source/integration_and_development/system_interfaces/api.rst
- source/management_and_operations/vm_management/vm_instances.rst
- source/open_cluster_deployment/kvm_node/kvm_driver.rst
> F OpenNebula/one#6636: Update documentation on  onevmmupdateconf

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6103.rst
> F OpenNebula/one#6636: Update resolved issues(CPU_MODEL/FEATURES)

- source/integration_and_development/system_interfaces/api.rst
> F OpenNebula/one#6623: Add snapshot-list cli command documentation

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6103.rst
> F OpenNebula/one#6623: update release note

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6103.rst
Closes [OpenNebula/one#6848](https://github.com/OpenNebula/one/issues/6848)
<hr>
> B OpenNebula/one#6848: Update doc

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6103.rst
Closes [OpenNebula/one#6852](https://github.com/OpenNebula/one/issues/6852)
<hr>
> B OpenNebula/one#6852: Update doc

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6103.rst
* Add OpenNebula/one#6806 to resolved issues
<hr>
> B OpenNebula/one#6806: Update resolved issues

- source/intro_release_notes/upgrades/upgrading_single.rst
Fixed the versions what migration package is included for one-6.10.
<hr>
> M #-: Fix ONE version what migration package is included for

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6103.rst
This PR fixes datastore, host and vnets tables in provision
<hr>
> B OpenNebula/One#6815: update resolved issues file

- source/intro_release_notes/release_notes/whats_new.rst
- source/open_cluster_deployment/storage_setup/nas_ds.rst
> Add AutoNFS to whats new

- source/intro_release_notes/release_notes/whats_new.rst
* Add OpenNebula/one#6674 to what's new
<hr>
> M OpenNebula/one#6674: Update what's new

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6103.rst
this PR adds issue 6714 to the resolved issue file
<hr>
> F OpenNebula/One#6714: update resolved issue file

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6103.rst
Update resolved issues file 
<hr>
> F OpenNebula/One#6724: update resolved issue

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6103.rst
This PR adds issue 6639 to the resolved issues file
<hr>
> F OpenNebula/One#6639: update resolved issues file

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6103.rst
> B OpenNebula/one#6831: Update resolved issues (VM save)

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6103.rst
* Add OpenNebula/one#6844 to resolved issues
<hr>
> B OpenNebula/one#6844: Update resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6103.rst
* Add OpenNebula/one#6839 to resolved issues
<hr>
> B OpenNebula/one#6839: Update resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6103.rst
* Add OpenNebula/one#6435 to resolved issues
<hr>
> F OpenNebula/one#6435: Update resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6103.rst
Release note for 6786 bug
<hr>
> B OpenNebula/one#6786: adding doc from 6786 bug

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6103.rst
Add several issues to 6.10.3 resolved: OpenNebula/one#6547, OpenNebula/one#6741, OpenNebula/one#6583, OpenNebula/one#2109
<hr>
> F #-: Update several resolved_issues

- source/intro_release_notes/release_notes/whats_new.rst
- source/management_and_operations/end-user_web_interfaces/fireedge_sunstone.rst
This PR adds the documentation for the issue 5969
<hr>
> F OpenNebula/one#5969: uses an available port

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6103.rst
Add 6799 to resolved issues
<hr>
> B OpenNebula/one#6799: Add 6799 to resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6103.rst
Add 6895 to resolve issues.
<hr>
> B OpenNebula/one#6895: Add 6895 to resolved issues

- source/intro_release_notes/release_notes/whats_new.rst
This PR adds issue 6781 from 6.10 to master
<hr>
> B OpenNebula/One#6781: add issue 6781 in whats news file.

- source/intro_release_notes/release_notes/whats_new.rst
This PR adds the documentation of the issue 6927
<hr>
> F OpenNebula/One#6927: filter ds when deploy a VM

- source/intro_release_notes/release_notes/whats_new.rst
this PR adds the documentation of issue 6461
<hr>
> F OpenNebula/One#6410: fix text in schedule actions

- source/marketplace/public_marketplaces/opennebula.rst
The information on the Community MP was added. Requirements removed.
<hr>
> M #-: Add an information on the Community MP

- source/marketplace/public_marketplaces/opennebula.rst
Minor retouch for style for info on marketplaces
<hr>
> M #-: Touch Community MP info for style

- source/intro_release_notes/release_notes/whats_new.rst
added documentation of issue 6643 
<hr>
> F OpenNebula/One#6643: show more labels in cards

- source/installation_and_configuration/opennebula_services/fireedge.rst
- source/installation_and_configuration/opennebula_services/monitoring.rst
- source/installation_and_configuration/opennebula_services/oned.rst
- source/installation_and_configuration/opennebula_services/oneflow.rst
- source/installation_and_configuration/opennebula_services/onegate.rst
- source/installation_and_configuration/opennebula_services/scheduler.rst
For each OpenNebula Service, add a note above the table listing the service's config file parameters, specifying where to find changes to config options in maintenance releases.
<hr>
> M #-: Add callouts config file changes in maintenance releases

- source/intro_release_notes/release_notes/arm64_beta.rst
- source/intro_release_notes/release_notes/index.rst
- source/open_cluster_deployment/kvm_node/kvm_driver.rst
- source/open_cluster_deployment/kvm_node/kvm_node_installation.rst
- source/open_cluster_deployment/kvm_node/overview.rst
> F #-: Add ARM64 specifics, add release notes

- source/installation_and_configuration/automatic_deployment/one_deploy_tutorial_local_ds.rst
- source/installation_and_configuration/automatic_deployment/one_deploy_tutorial_shared_ds.rst
Updates the one-deploy-related documentation to use hatch/uv
<hr>
> F OpenNebula/one-apps#109: Update one-deploy hatch/uv documentation

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6103.rst
Update resolved issues on 6.10.3. Change config files in release notes.
<hr>
> M #-: Resolved issues. Config files.

- source/installation_and_configuration/opennebula_services/fireedge.rst
Updated FireEdge configuration download link
<hr>
> Updated fireedge configuracion file

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6103.rst
- source/intro_release_notes/release_notes_enterprise/resolved_issues_6104.rst
Fix references in release notes.
<hr>
> M #-: Fix issues in release notes

- source/intro_release_notes/release_notes/whats_new.rst
Enables/Disables the buttons depending on the host status
<hr>
> F OpenNebula/One#6792: enable/disable host button

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6104.rst
> M #-: Update milestone link

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6104.rst
Add resolved issue for #3213 
<hr>
> B #6666: Restic passwords: remove quotes and sanitize

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6104.rst
Add resolved issue for [6948](https://github.com/OpenNebula/docs/pull/6948)
<hr>
> B OpenNebula/one#6948: Add 6948 to resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6104.rst
Add resolved issue for [6975](https://github.com/OpenNebula/one/issues/6975)
<hr>
> B OpenNebula/one#6975: Add 6975 to resolved issues

- source/intro_release_notes/release_notes/whats_new.rst
> B OpenNebula/One#6892: Add upper limit check for passwords.

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6104.rst
> B OpenNebula/one#6858: Add 6858 to resolved issues.

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6104.rst
> B OpenNebula/one#6993: Add 6993 to resolved issues

- source/ext/spellchecking/wordlists/opennebula.txt
- source/open_cluster_deployment/storage_setup/index.rst
- source/open_cluster_deployment/storage_setup/netapp_ds.rst
First version of NetApp documentation
Should be pretty complete but if there are any changes during testing I'll update it.
> F OpenNebula/one#6753: first version of NetApp documentation

- source/intro_release_notes/release_notes/platform_notes.rst
- source/intro_release_notes/upgrades/upgrading_single.rst
> M #: Add note about mixed platform environments

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6104.rst
Add ability to add existing users to existing groups release notes
<hr>
> F OpenNebula/one#6980: Add ability to add existing users to existing groups

- source/intro_release_notes/release_notes/whats_new.rst
> B OpenNebula/one#6952: Update what's new (filterflag)

- source/open_cluster_deployment/networking_setup/openvswitch.rst
Fixed some typos and commands. Added references and explanations for "hidden" required operations.
<hr>
> M #: Improve dpdk setup doc

- source/intro_release_notes/release_notes/platform_notes.rst
> M #-: Bump supported Ceph version

- source/open_cluster_deployment/networking_setup/openvswitch.rst
> M #: Fix copypaste

- source/open_cluster_deployment/networking_setup/vxlan.rst
> M #-: Add VXLAN UDP ports and bridge limits

- source/intro_release_notes/release_notes/whats_new.rst
> F OpenNebula/one#6699: Add note about onedb purge-history change

- source/open_cluster_deployment/storage_setup/lvm_drivers.rst
> LVM thin + remove references to fs_lvm

- source/installation_and_configuration/frontend_installation/install.rst
- source/installation_and_configuration/ha/frontend_ha.rst
- source/management_and_operations/capacity_planning/affinity.rst
- source/management_and_operations/capacity_planning/overcommitment.rst
- source/management_and_operations/capacity_planning/overview.rst
- source/management_and_operations/capacity_planning/quotas.rst
- source/management_and_operations/capacity_planning/scheduler/configuration.rst
- source/management_and_operations/capacity_planning/scheduler/drs.rst
- source/management_and_operations/capacity_planning/scheduler/overview.rst
- source/management_and_operations/capacity_planning/scheduler/rank_scheduler.rst
- source/management_and_operations/monitor_alert/configuration.rst
- source/management_and_operations/monitor_alert/forecast.rst
- source/management_and_operations/monitor_alert/metrics.rst
- source/management_and_operations/monitor_alert/overview.rst
- source/management_and_operations/monitor_alert/prometheus/alerts.rst
- source/management_and_operations/monitor_alert/prometheus/grafana.rst
- source/management_and_operations/monitor_alert/prometheus/install.rst
- source/management_and_operations/monitor_alert/prometheus/metrics.rst
- source/management_and_operations/monitor_alert/prometheus/overview.rst
- source/overview/opennebula_concepts/opennebula_overview.rst
- Style review for docs describing the new scheduler, and other minor style modifications in the sections "Capacity Planning"  and "Monitoring and Alerting"
- Update mentions of the old scheduler throughout the docs site to conform to the new scheduler
There still a few modifications to be made based on updated technical info.
This would only apply to master.
<hr>
> M #:- Style review for new scheduler docs

- source/intro_release_notes/release_notes/whats_new.rst
> B OpenNebula/one#6996: Update what's new (duplicit Sched Actions)

- source/open_cluster_deployment/storage_setup/lvm_drivers.rst
Minor modifications for style for new paragraphs introduced with LVM thin functionality.
Would apply only to master.
<hr>
> M #-: Minor style changes in Thin LVM

- source/installation_and_configuration/ha/frontend_ha.rst
- source/integration_and_development/references/compile.rst
- source/open_cluster_deployment/kvm_node/kvm_driver.rst
Modified technical details for the new scheduler framework:
- KVM tuning: `MAX_HOST` parameter in `rank.conf` file
- HA server sync: Files updated by the `onezone serversync` command
- Compiling from source: Deleted error message from old scheduler files
- Few minor style updates
<hr>
> M #-: Modify technical details for new scheduler

- source/ext/spellchecking/wordlists/opennebula.txt
- source/marketplace/index.rst
- source/marketplace/ova_management/import_ova.rst
- source/marketplace/ova_management/index.rst
- source/marketplace/ova_management/overview.rst
Documentation for OVA management using the oneswap command.
<hr>
> OVA management

- source/installation_and_configuration/configuration_management/conflicts.rst
> B OpenNebula/one#6521: Reverse patch_safe logic

- source/marketplace/index.rst
- source/marketplace/ova_management/import_ova.rst
- source/marketplace/ova_management/index.rst
- source/marketplace/ova_management/overview.rst
Add documentation for --vmdk option in oneswap import. Also added additional parameters to the oneswap import, previosly missing.
<hr>
> M #-: Add docs for VMDK import using OneSwap

- source/management_and_operations/end-user_web_interfaces/fireedge_sunstone.rst
this PR adds the note that when using RDP you must have a service such as XRDP running on the VM.
<hr>
> M #~: RDP note

- source/open_cluster_deployment/kvm_node/pci_passthrough.rst
Add note to make clear the user needs to update the ``pci.conf`` file only in the Frontend and then update drivers.
<hr>
> M #-: Add note on PCI passthrough driver configuration

- source/management_and_operations/end-user_web_interfaces/fireedge_sunstone.rst
This PR adds in the RDP note some adjustments to be taken into account
<hr>
> M #~: fix note RDP guacamole

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6105.rst
Add issue [#6873](https://github.com/OpenNebula/one/issues/6873) on resolved issues for version 6.10.5
<hr>
> B OpenNebula/one#6873: Updated resolved issues for 6.10.5

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6105.rst
* Add OpenNebula/one#7060 to resolved issues.
<hr>
> B OpenNebula/one#7060: Update resolved issues

- source/_templates/thelayout.html
> M #-: Remove GA

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6105.rst
Fixed the ownership issue when instanciate VM
<hr>
> B OpenNebula/one#7013: fix ownership issue when instanciate VM

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6105.rst
Updated the translation text in constant module
<hr>
> F OpenNebula/one-ee#7222: updated translation text

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6105.rst
* Add OpenNebula/one#6867 to resolved issues.
<hr>
> F OpenNebula/one#6867: Update resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6105.rst
* Add OpenNebula/one#7158 to resolved issues
<hr>
> B OpenNebula/one#7158: Update resolved issues

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6105.rst
Fixed Security Group Rule Description for IPs
<hr>
> B OpenNebula/one#7186 fix security group rule description

- source/intro_release_notes/release_notes_enterprise/resolved_issues_6105.rst
Fixed rule addition for security group creation.
<hr>
> B OpenNebula#7206 fixed secruity group rule addition
